/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.components;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import javax.swing.Timer;

/**
 *
 * @author Hai
 */
public class DrawVictoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrawVictoryPanel
     */
    private float scale = 0.1f;
    private float alpha = 0.0f;
    private Timer timer;
    public DrawVictoryPanel() {
        timer = new Timer(30, (ActionEvent e) -> {
            boolean repaintNeeded = false;

            if (scale < 1.0f) {
                scale += 0.02f;
                repaintNeeded = true;
            }

            if (alpha < 1.0f) {
                alpha += 0.02f;
                repaintNeeded = true;
            }

            if (repaintNeeded) {
                repaint();
            } else {
                timer.stop(); // Stoppe le timer quand l’animation est terminée
            }
        });
        timer.start();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g.create();

        // Enable anti-aliasing
        g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                             RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

        String text = "VICTORY";
        g2d.setFont(getFont().deriveFont(Font.BOLD, 80 * scale));
        float safeAlpha = Math.max(0f, Math.min(1f, alpha));
        g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, safeAlpha));

        g2d.setColor(Color.YELLOW);

        FontMetrics fm = g2d.getFontMetrics();
        int x = (getWidth() - fm.stringWidth(text)) / 2;
        int y = (getHeight() + fm.getAscent()) / 2;

        g2d.drawString(text, x, y);
        g2d.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
