/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.components;

import boundary.BoundaryJeu;
import boundary.Plateau;
import noyau.Pirate;

/**
 *
 * @author vince
 */
public class JInfoJoueurVersionAggrandi extends javax.swing.JPanel {
    private String nom;
    int idPirate;
    private Pirate pirate;
    private JMainJoueur jMainJoueur;

    /**
     * Creates new form JJoueurInfo
     */
    public JInfoJoueurVersionAggrandi() {
        initComponents();
        setOpaque(false);
    }
    
    public void finTour() {
        Plateau p = (Plateau) getParent().getParent();
        BoundaryJeu boundaryJeu = p.getBoundaryJeu(); 
        setHP(boundaryJeu.getPirateHp(idPirate));
        setPP(boundaryJeu.getPiratePp(idPirate));
        repaint();
    }
    
    private void setHP(int value) {
        jPointDeVie.setEtat(value >= 1);
        jPointDeVie1.setEtat(value >= 2);
        jPointDeVie2.setEtat(value >= 3);
        jPointDeVie3.setEtat(value >= 4);
        jPointDeVie4.setEtat(value >= 5);
    }
    
    private void setPP(int value) {
        jaugePopularite.setImage("PointPopularite" + value + ".png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPointDeVie = new boundary.components.JPointDeVie();
        jPointDeVie1 = new boundary.components.JPointDeVie();
        jPointDeVie2 = new boundary.components.JPointDeVie();
        jPointDeVie3 = new boundary.components.JPointDeVie();
        jPointDeVie4 = new boundary.components.JPointDeVie();
        jaugePopularite = new boundary.components.JPanelWithBackground();

        setPreferredSize(new java.awt.Dimension(138, 148));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPointDeVie.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVieLayout = new javax.swing.GroupLayout(jPointDeVie);
        jPointDeVie.setLayout(jPointDeVieLayout);
        jPointDeVieLayout.setHorizontalGroup(
            jPointDeVieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPointDeVieLayout.setVerticalGroup(
            jPointDeVieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPointDeVie, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 20, 30));

        jPointDeVie1.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVie1Layout = new javax.swing.GroupLayout(jPointDeVie1);
        jPointDeVie1.setLayout(jPointDeVie1Layout);
        jPointDeVie1Layout.setHorizontalGroup(
            jPointDeVie1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPointDeVie1Layout.setVerticalGroup(
            jPointDeVie1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPointDeVie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 20, 30));

        jPointDeVie2.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVie2Layout = new javax.swing.GroupLayout(jPointDeVie2);
        jPointDeVie2.setLayout(jPointDeVie2Layout);
        jPointDeVie2Layout.setHorizontalGroup(
            jPointDeVie2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPointDeVie2Layout.setVerticalGroup(
            jPointDeVie2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPointDeVie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 20, 30));

        jPointDeVie3.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVie3Layout = new javax.swing.GroupLayout(jPointDeVie3);
        jPointDeVie3.setLayout(jPointDeVie3Layout);
        jPointDeVie3Layout.setHorizontalGroup(
            jPointDeVie3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPointDeVie3Layout.setVerticalGroup(
            jPointDeVie3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPointDeVie3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 20, 30));

        jPointDeVie4.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVie4Layout = new javax.swing.GroupLayout(jPointDeVie4);
        jPointDeVie4.setLayout(jPointDeVie4Layout);
        jPointDeVie4Layout.setHorizontalGroup(
            jPointDeVie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPointDeVie4Layout.setVerticalGroup(
            jPointDeVie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPointDeVie4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 30));

        javax.swing.GroupLayout jaugePopulariteLayout = new javax.swing.GroupLayout(jaugePopularite);
        jaugePopularite.setLayout(jaugePopulariteLayout);
        jaugePopulariteLayout.setHorizontalGroup(
            jaugePopulariteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jaugePopulariteLayout.setVerticalGroup(
            jaugePopulariteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        add(jaugePopularite, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, 130));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private boundary.components.JPointDeVie jPointDeVie;
    private boundary.components.JPointDeVie jPointDeVie1;
    private boundary.components.JPointDeVie jPointDeVie2;
    private boundary.components.JPointDeVie jPointDeVie3;
    private boundary.components.JPointDeVie jPointDeVie4;
    private boundary.components.JPanelWithBackground jaugePopularite;
    // End of variables declaration//GEN-END:variables
}
