/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.components;

import java.util.ArrayList;
import java.util.List;
import noyau.Carte;
import noyau.Pirate;

/**
 *
 * @author vince
 */
public class JInfoJoueur extends javax.swing.JPanel {
    
    private Pirate pirate;
    private JMainJoueur jMainJoueur;

    /**
     * Creates new form JJoueurInfo
     */
    public JInfoJoueur() {
        initComponents();
        setOpaque(false);
    }
    
    public void setPirate(Pirate pirate, JMainJoueur jMainJoueur) {
        this.pirate = pirate;
        this.jMainJoueur = jMainJoueur;
    }
    
    public void finTour() {
        setHP(pirate.getHP());
        setPP(pirate.getPP());
    }
    
    public void retournerCartes() {
        List<JCarte> mainJoueur = jMainJoueur.getMainJoueur();
        
        for (JCarte jCarte : mainJoueur) {
            jCarte.changeCardFace();
        }
    }
    
    private void setHP(int value) {
        jPointDeVie.setEtat(value >= 1);
        jPointDeVie2.setEtat(value >= 2);
        jPointDeVie3.setEtat(value >= 3);
        jPointDeVie4.setEtat(value >= 4);
        jPointDeVie5.setEtat(value >= 5);
    }
    
    private void setPP(int value) {
        jaugePopularite.setImage("PointPopularite" + value + ".png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPointDeVie = new boundary.components.JPointDeVie();
        jPointDeVie2 = new boundary.components.JPointDeVie();
        jPointDeVie3 = new boundary.components.JPointDeVie();
        jPointDeVie4 = new boundary.components.JPointDeVie();
        jPointDeVie5 = new boundary.components.JPointDeVie();
        jaugePopularite = new boundary.components.JPanelWithBackground();

        setPreferredSize(new java.awt.Dimension(138, 148));
        setLayout(new java.awt.GridBagLayout());

        jPointDeVie.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVieLayout = new javax.swing.GroupLayout(jPointDeVie);
        jPointDeVie.setLayout(jPointDeVieLayout);
        jPointDeVieLayout.setHorizontalGroup(
            jPointDeVieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPointDeVieLayout.setVerticalGroup(
            jPointDeVieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jPointDeVie, gridBagConstraints);

        jPointDeVie2.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVie2Layout = new javax.swing.GroupLayout(jPointDeVie2);
        jPointDeVie2.setLayout(jPointDeVie2Layout);
        jPointDeVie2Layout.setHorizontalGroup(
            jPointDeVie2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPointDeVie2Layout.setVerticalGroup(
            jPointDeVie2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jPointDeVie2, gridBagConstraints);

        jPointDeVie3.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVie3Layout = new javax.swing.GroupLayout(jPointDeVie3);
        jPointDeVie3.setLayout(jPointDeVie3Layout);
        jPointDeVie3Layout.setHorizontalGroup(
            jPointDeVie3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPointDeVie3Layout.setVerticalGroup(
            jPointDeVie3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jPointDeVie3, gridBagConstraints);

        jPointDeVie4.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVie4Layout = new javax.swing.GroupLayout(jPointDeVie4);
        jPointDeVie4.setLayout(jPointDeVie4Layout);
        jPointDeVie4Layout.setHorizontalGroup(
            jPointDeVie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPointDeVie4Layout.setVerticalGroup(
            jPointDeVie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jPointDeVie4, gridBagConstraints);

        jPointDeVie5.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVie5Layout = new javax.swing.GroupLayout(jPointDeVie5);
        jPointDeVie5.setLayout(jPointDeVie5Layout);
        jPointDeVie5Layout.setHorizontalGroup(
            jPointDeVie5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPointDeVie5Layout.setVerticalGroup(
            jPointDeVie5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jPointDeVie5, gridBagConstraints);

        jaugePopularite.setOpaque(false);
        jaugePopularite.setPreferredSize(new java.awt.Dimension(119, 119));

        javax.swing.GroupLayout jaugePopulariteLayout = new javax.swing.GroupLayout(jaugePopularite);
        jaugePopularite.setLayout(jaugePopulariteLayout);
        jaugePopulariteLayout.setHorizontalGroup(
            jaugePopulariteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        jaugePopulariteLayout.setVerticalGroup(
            jaugePopulariteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        add(jaugePopularite, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private boundary.components.JPointDeVie jPointDeVie;
    private boundary.components.JPointDeVie jPointDeVie2;
    private boundary.components.JPointDeVie jPointDeVie3;
    private boundary.components.JPointDeVie jPointDeVie4;
    private boundary.components.JPointDeVie jPointDeVie5;
    private boundary.components.JPanelWithBackground jaugePopularite;
    // End of variables declaration//GEN-END:variables
}
