/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.components;

import java.awt.Graphics;
import java.awt.Image;

import javax.swing.ImageIcon;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.util.LinkedList;
import java.util.Objects;
import java.util.Queue;


/**
 *
 * @author leo et yannf
 */
public class JLancerPiece extends javax.swing.JPanel {
    private ImageIcon iconPile;
    private ImageIcon iconFace;
    private ImageIcon lancer;
    private String etat = "0";
    private Image currentImage = null;
    private boolean animationInProgress = false;
    private Queue<String> animationQueue = new LinkedList<>();

    /**
     * Creates new form lancerPiece
     */
    public JLancerPiece() {
        initComponents();
        initImage();
    }

    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);

        if (currentImage != null){
            g.drawImage(currentImage, 0, 0, this);
        }    
    }

    public void setEtat(String nEtat){
        if (!nEtat.equals("P") && !nEtat.equals("F")) return;

        // If animation is already in progress, queue this request
        if (animationInProgress) {
            animationQueue.add(nEtat);
            return;
        }

        // Start the animation
        startAnimation(nEtat);
    }

    private void startAnimation(String nEtat) {
        animationInProgress = true;
        this.etat = nEtat;

        // Start the animation sequence
        currentImage = lancer.getImage();
        repaint();

        // Wait and then show result using a Swing Timer
        Timer t1 = new Timer(2500, (ActionEvent e) -> {
            currentImage = etat.equals("P") ? iconPile.getImage() : iconFace.getImage();
            repaint();
            // Reset after another delay
            Timer t2 = new Timer(3400, (ActionEvent e2) -> {
                etat = "0";
                currentImage = null;
                repaint();

                // Animation is complete, check if there are more in the queue
                animationInProgress = false;
                if (!animationQueue.isEmpty()) {
                    String nextAnimation = animationQueue.poll();
                    startAnimation(nextAnimation);
                }
            });
            t2.setRepeats(false);
            t2.start();
        });
        t1.setRepeats(false);
        t1.start();
    }

    private void initImage(){
        lancer = new ImageIcon(Objects.requireNonNull(getClass().getResource("/Animation-Lancer.gif")));
        iconFace = new ImageIcon(Objects.requireNonNull(getClass().getResource("/Animation-Noir.gif")));
        iconPile = new ImageIcon(Objects.requireNonNull(getClass().getResource("/Animation-Jaune.gif")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
