/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.components;

import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.util.ArrayList;
import java.util.List;
import noyau.CategorieCarte;

/**
 *
 * @author yannf
 */
public class JMainJoueur extends javax.swing.JPanel {
    private List<JCarte> mainJoueur = new ArrayList<>();
    
    /**
     * Creates new form JMainJoueur
     */
    public JMainJoueur() {
        initComponents();
    }

    public void ajouterCarte(String nomCarte){
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.gridy = 0;
        gbc.gridx = mainJoueur.size();
        JCarte carte = createCarte(nomCarte);
                
        mainJoueur.add(carte);
        this.add(carte, gbc);
        this.revalidate();
        this.repaint();
    }
    
    private JCarte createCarte(String nomCarte) {
        
        JCarte newCarte = new boundary.components.JCarte();
        newCarte.setMinimumSize(new java.awt.Dimension(84, 117));
        newCarte.setPreferredSize(new java.awt.Dimension(84, 117));
        newCarte.ajouterAttribut(nomCarte, CategorieCarte.POPULARITE, "", this);//Ajout Enum
        //newCarte.setImage("Card1Front" + nomCarte + ".png");

        javax.swing.GroupLayout newCarteLayout = new javax.swing.GroupLayout(newCarte);
        newCarte.setLayout(newCarteLayout);
        newCarteLayout.setHorizontalGroup(
            newCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );
        newCarteLayout.setVerticalGroup(
            newCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        newCarte.changeCardFace();
        return newCarte;
    }
    
    
    public void deleteCard(String nomCarte){
        for(JCarte carte : mainJoueur){
            if (nomCarte.equals(carte.getNomCarte())){
                return;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
