/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.components;

import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.util.ArrayList;
import java.util.List;

import noyau.BasicCategorie;
import noyau.ICategorieCarte;

/**
 *
 * @author yannf, leo et vincent
 */
public class JMainJoueur extends javax.swing.JPanel {
    private final List<JCarte> mainJoueur = new ArrayList<>();
    private int idPirate;
    
    /**
     * Creates new form JMainJoueur
     */
    public JMainJoueur() {
        initComponents();
    }

    public void ajouterCarte(String nomCarte, int carteID, ICategorieCarte type, String description, BasicCategorie categorie){
        JCarte carte = createCarte(nomCarte, carteID, type, description, categorie);
        ajouterJCarte(carte);
    }
    
    private JCarte createCarte(String nomCarte, int carteID, ICategorieCarte type, String description, BasicCategorie zoneDepot) {
        
        JCarte newCarte = new boundary.components.JCarte();

        newCarte.ajouterAttribut(nomCarte, carteID, type, description,
                zoneDepot, this);
        javax.swing.GroupLayout newCarteLayout = new javax.swing.GroupLayout(newCarte);
        newCarte.setLayout(newCarteLayout);
        newCarteLayout.setHorizontalGroup(
            newCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );
        newCarteLayout.setVerticalGroup(
            newCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        newCarte.changeCardFace();
        return newCarte;
    }

    private void redimensionnerCarte(JCarte carte, int totalCartes) {
        int largeurMain = this.getWidth();

        int margeTotaleParCarte = 20;
        int largeurDisponible = largeurMain - (totalCartes * margeTotaleParCarte);
        int largeurCarte = largeurDisponible / totalCartes;

        int baseWidth = 84;

        double scale = 1.0;
        if (largeurMain > 420) {
            scale = 1.5;
        }

        int width = Math.min((int) (baseWidth * scale), largeurCarte);
        int height = (int) (width * 1.4);

        carte.setMinimumSize(new java.awt.Dimension(width, height));
        carte.setPreferredSize(new java.awt.Dimension(width, height));
    }
    
    public void deleteCard(JCarte jcarte){
        if (mainJoueur.contains(jcarte)) {
            mainJoueur.remove(jcarte);
            setGridCartes();
            
        } else {
            throw new IllegalArgumentException("Carte non trouvée dans la main du joueur\n");
        }
    }
    
    public void ajouterJCarte(JCarte jCarte) {
        mainJoueur.add(jCarte);
        setGridCartes();

        this.revalidate();
        this.repaint();
    }
    
    public void setGridCartes() {
        this.removeAll();
        int totalCartes = mainJoueur.size();
        
        for (int i = 0; i < totalCartes; i++) {
            JCarte jcarte = mainJoueur.get(i);
            redimensionnerCarte(jcarte, totalCartes);
            
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.insets = new Insets(5, 5, 5, 5);
            gbc.gridy = 0;
            gbc.gridx = i;
            gbc.fill = GridBagConstraints.HORIZONTAL;
            this.add(jcarte, gbc);
        }
        
        this.revalidate();
        this.repaint();
    }
    
    public List<JCarte> getMainJoueur() {
        return mainJoueur;
    }
    
    public void setIdPirate (int idPirate){
        this.idPirate = idPirate;
    }
    
    @Override
    public void setEnabled(boolean value){
        super.setEnabled(value);
        for(JCarte carte : mainJoueur){
            carte.setEnabled(value);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 0));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMinimumSize(new java.awt.Dimension(420, 160));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(420, 160));
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents

    public boolean deleteCardName(String cardName) {
       for(JCarte carte : mainJoueur){
            if (cardName.equals(carte.getNomCarte())){
                deleteCard(carte);
                return true;
            }
        }
       return false;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
