/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.components;

import java.awt.GridBagConstraints;
import static java.awt.GridBagConstraints.BOTH;
import java.awt.Insets;
import java.util.ArrayList;
import java.util.List;

import noyau.BasicCategorie;
import noyau.ICategorieCarte;

/**
 *
 * @author yannf et leo, retouche vincent
 */
public class JMainJoueur extends javax.swing.JPanel {
    private List<JCarte> mainJoueur = new ArrayList<>();
    private int idPirate;
    
    /**
     * Creates new form JMainJoueur
     */
    public JMainJoueur() {
        initComponents();
    }

    public void ajouterCarte(String nomCarte, int carteID, ICategorieCarte type, String description, BasicCategorie categorie){
        //System.out.println("JMainJoueur ajouterCarte , nomCarte = " + nomCarte + "\n");
        JCarte carte = createCarte(nomCarte, carteID, type, description, categorie);
        ajouterJCarte(carte);
    }
    
    private JCarte createCarte(String nomCarte, int carteID, ICategorieCarte type, String description, BasicCategorie zoneDepot) {
        
        JCarte newCarte = new boundary.components.JCarte();
        newCarte.setMinimumSize(new java.awt.Dimension(84, 117));
        newCarte.setPreferredSize(new java.awt.Dimension(84, 117));
        //System.out.println("JMainJoueur createCarte , nomCarte = " + nomCarte + "\n");
        newCarte.ajouterAttribut(nomCarte, carteID, type, description,
                zoneDepot, this);
        //newCarte.setImage("Card1Front" + newCarte.getCategorie().toString() + ".png");
        //System.out.println("JMainJoueur createCarte , nomCarte = " + newCarte.getNomCarte() + "\n");
        javax.swing.GroupLayout newCarteLayout = new javax.swing.GroupLayout(newCarte);
        newCarte.setLayout(newCarteLayout);
        newCarteLayout.setHorizontalGroup(
            newCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );
        newCarteLayout.setVerticalGroup(
            newCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        newCarte.changeCardFace();
        return newCarte;
    }
    
                    // ça sert ????? Aucune ref dans la main du joueur. visiblement pas
    public void deleteCard(String nomCarte){
        for(JCarte carte : mainJoueur){
            if (nomCarte.equals(carte.getNomCarte())){
                //TODO
                return;
            }
        }
    }
    
    public void ajouterJCarte(JCarte jCarte){
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.gridy = 0;
        gbc.gridx = mainJoueur.size();
        gbc.fill = BOTH;
        gbc.weightx = 1;
        gbc.weighty = 1;
        mainJoueur.add(jCarte);
        jPanel1.add(jCarte, gbc);
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    
    public List<JCarte> getMainJoueur() {
        return mainJoueur;
    }
    
    public void setIdPirate (int idPirate){
        this.idPirate = idPirate;
    }
    
    @Override
    public void setEnabled(boolean value){
        super.setEnabled(value);
        for(JCarte carte : mainJoueur){
            carte.setEnabled(value);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 0));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMinimumSize(new java.awt.Dimension(0, 0));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(0, 0));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
