/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.components;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author yannf
 */
public class JPioche extends javax.swing.JPanel {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private transient Image defaultIcon = null;
    private transient Image hoverIcon = null;
    private boolean isHover = false;
    
    /**
     * Creates new form JPioche
     */
    public JPioche() {
        initComponents();
        setImage();
    }
    
    
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D)g;
        
        // Draw the background image.
        if(isHover && hoverIcon != null && this.isEnabled()){    
            g2d.drawImage(hoverIcon, 0, 0, getWidth(), getHeight(), this);
        } else if(defaultIcon != null ){
            g2d.drawImage(defaultIcon, 0, 0, getWidth(), getHeight(), this);
        }
    }
    
    private void setImage(){
        try{
            defaultIcon = ImageIO.read(new File("src/main/resources/PiocheNormal.png"));
            hoverIcon = ImageIO.read(new File("src/main/resources/PiocheHover.png"));
        } catch (IOException e){
            String userDirectory = new File("").getAbsolutePath();
            System.out.print("Pioche not found : " + userDirectory);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered();
            }
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered() {//GEN-FIRST:event_formMouseEntered
        isHover = true;
        repaint();
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited() {//GEN-FIRST:event_formMouseExited
        isHover = false;
        repaint();
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
