/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.components;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Polygon;
import java.awt.RenderingHints;

/**
 *
 * @author choue
 */
public class JPointDeVie extends javax.swing.JPanel {
    private boolean plein = true; 
    
    /**
     * Creates new form JPointDeVie
     */
    public JPointDeVie() {
        initComponents();
        setPreferredSize(new Dimension(20, 20)); //24x24 Normaly
        setOpaque(false);
    }

    public void setEtat(boolean plein) {
        this.plein = plein;
        repaint();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;

        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(plein ? Color.RED : Color.GRAY);

        int w = getWidth();
        int h = getHeight();
        int demi = w / 2;
        int arcHauteur = h / 2;

        // Demi-cercles du haut
        g2.fillArc(0, 0, demi, arcHauteur, 0, 180);
        g2.fillArc(demi, 0, demi, arcHauteur, 0, 180);

        // Triangle qui part juste sous les arcs
        Polygon triangle = new Polygon();
        triangle.addPoint(0, arcHauteur / 2 );         // bord gauche, coller à la base de l’arc
        triangle.addPoint(w, arcHauteur / 2 );         // bord droit
        triangle.addPoint(demi, h);                   // pointe basse
        g2.fillPolygon(triangle);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
