/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.components;


import java.awt.Image;
import noyau.CategorieCarte;

/**
 *
 * @author yannf
 */
public class JZoneDepot extends javax.swing.JPanel {
    private Image carte;
    private String nomPirate;
    private CategorieCarte type;
    
    /**
     * Creates new form JZoneDepot
     */
    public JZoneDepot() {
        initComponents();
    }

    public void createZoneDepot(String nomPirate, CategorieCarte type){
        this.nomPirate = nomPirate;
        this.type = type;
    }
    
    public boolean ajouterCarte (JCarte carte){
        return true;


    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGap(0, 81, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)

        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
