/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.components;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Rectangle;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

import noyau.BasicCategorie;


/**
 * 
 * @author leo
 */
public class JZoneInteraction extends javax.swing.JPanel {
    
    private boolean carteDedans = false;
    /**
     * Creates new form JZoneInteraction
     */
    public JZoneInteraction() {
        initComponents();
        setBounds(500,200,150,150);
    }

    // Méthode pour vérifier si une carte a été déposée dans la zone
    public void verifierCarte(JCarte carte) {
        Point centre = carte.getCentreCarte();
        Rectangle zone = this.getBounds();

        boolean dedans = zone.contains(centre);
        if (dedans != carteDedans) {
            carteDedans = dedans;
            repaint();
        }
    }
    
    public boolean ajouteCarte (JCarte carte, Point p, JPanel panelPlateau, String pirate){
        Point pointInZoneIntract = SwingUtilities.convertPoint(panelPlateau, p, ZoneAction);
        Component[] lstComp = ZoneAction.getComponents();
        for(Component c : lstComp){
            if (c instanceof JZoneDepot dep){
                Point pointInDep = SwingUtilities.convertPoint(ZoneAction, pointInZoneIntract, dep);
                if (dep.contains(pointInDep)){
                    return dep.ajouterCarte(carte, pirate);
                }
            }
        }
        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ZoneAction = new javax.swing.JPanel();
        jZoneDepot1 = new boundary.components.JZoneDepot();
        jZoneDepot2 = new boundary.components.JZoneDepot();
        jZoneDepot3 = new boundary.components.JZoneDepot();
        jZoneDepot4 = new boundary.components.JZoneDepot();

        setBackground(new java.awt.Color(255, 153, 153));
        setOpaque(false);

        ZoneAction.setOpaque(false);
        ZoneAction.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout jZoneDepot1Layout = new javax.swing.GroupLayout(jZoneDepot1);
        jZoneDepot1.setLayout(jZoneDepot1Layout);
        jZoneDepot1Layout.setHorizontalGroup(
            jZoneDepot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        jZoneDepot1Layout.setVerticalGroup(
            jZoneDepot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 9, 20, 9);
        ZoneAction.add(jZoneDepot1, gridBagConstraints);

        javax.swing.GroupLayout jZoneDepot2Layout = new javax.swing.GroupLayout(jZoneDepot2);
        jZoneDepot2.setLayout(jZoneDepot2Layout);
        jZoneDepot2Layout.setHorizontalGroup(
            jZoneDepot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        jZoneDepot2Layout.setVerticalGroup(
            jZoneDepot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 9, 20, 9);
        ZoneAction.add(jZoneDepot2, gridBagConstraints);

        javax.swing.GroupLayout jZoneDepot3Layout = new javax.swing.GroupLayout(jZoneDepot3);
        jZoneDepot3.setLayout(jZoneDepot3Layout);
        jZoneDepot3Layout.setHorizontalGroup(
            jZoneDepot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        jZoneDepot3Layout.setVerticalGroup(
            jZoneDepot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 9, 20, 9);
        ZoneAction.add(jZoneDepot3, gridBagConstraints);

        javax.swing.GroupLayout jZoneDepot4Layout = new javax.swing.GroupLayout(jZoneDepot4);
        jZoneDepot4.setLayout(jZoneDepot4Layout);
        jZoneDepot4Layout.setHorizontalGroup(
            jZoneDepot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        jZoneDepot4Layout.setVerticalGroup(
            jZoneDepot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 9, 20, 9);
        ZoneAction.add(jZoneDepot4, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ZoneAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ZoneAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ZoneAction;
    private boundary.components.JZoneDepot jZoneDepot1;
    private boundary.components.JZoneDepot jZoneDepot2;
    private boundary.components.JZoneDepot jZoneDepot3;
    private boundary.components.JZoneDepot jZoneDepot4;
    // End of variables declaration//GEN-END:variables

    public void initZoneDepot(String nomPirate1, String nomPirate2) {
        jZoneDepot1.createZoneDepot(nomPirate1, BasicCategorie.POPULARITE);
        jZoneDepot2.createZoneDepot(nomPirate1, BasicCategorie.ATTAQUE);
        jZoneDepot3.createZoneDepot(nomPirate2, BasicCategorie.ATTAQUE);
        jZoneDepot4.createZoneDepot(nomPirate2, BasicCategorie.POPULARITE);
    }
}
