/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.components;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Rectangle;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import noyau.CategorieCarte;


/**
 *
 * @author choue
 */
public class JZoneInteraction extends javax.swing.JPanel {
    
    private int origine = 0;
    private boolean carteDedans = false;
    /**
     * Creates new form JZoneInteraction
     */
    public JZoneInteraction() {
        initComponents();
        //setBackground(Color.PINK);
        setBounds(500,200,150,150);
        jZoneDepot1.setName("Dep1");
        jZoneDepot1.createZoneDepot("Pirate1", CategorieCarte.POPULARITE);
        jZoneDepot2.setName("Dep2");
        jZoneDepot1.createZoneDepot("Pirate1", CategorieCarte.ATTAQUE);
        jZoneDepot3.setName("Dep3");
        jZoneDepot1.createZoneDepot("Pirate2", CategorieCarte.ATTAQUE);
        jZoneDepot4.setName("Dep4");
        jZoneDepot1.createZoneDepot("Pirate2", CategorieCarte.POPULARITE);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;

        g2.setColor(carteDedans ? Color.BLUE : Color.PINK);
        g2.fillRect(0, 0, getWidth(), getHeight());

        //g2.setColor(Color.BLACK);
        //g2.drawRect(0, 0, getWidth() - 1, getHeight() - 1);
    }

    // Méthode pour vérifier si une carte a été déposée dans la zone
    public void verifierCarte(JCarte carte) {
        Point centre = carte.getCentreCarte();
        Rectangle zone = this.getBounds();

        boolean dedans = zone.contains(centre);
        if (dedans != carteDedans) {
            carteDedans = dedans;
            repaint();
        }
    }
    
    public boolean ajouteCarte (JCarte carte, Point p, JPanel panelPlateau){
        Point pointInZoneIntract = SwingUtilities.convertPoint(panelPlateau, p, jPanel1);
        Component[] lstComp = jPanel1.getComponents();
        for(Component c : lstComp){
            if (c instanceof JZoneDepot dep){
                Point pointInDep = SwingUtilities.convertPoint(jPanel1, pointInZoneIntract, dep);
                if (dep.contains(pointInDep)){
                    return dep.ajouterCarte(carte);
                }
            }
        }
        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jZoneDepot1 = new boundary.components.JZoneDepot();
        jZoneDepot2 = new boundary.components.JZoneDepot();
        jZoneDepot3 = new boundary.components.JZoneDepot();
        jZoneDepot4 = new boundary.components.JZoneDepot();

        setBackground(new java.awt.Color(255, 153, 153));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jZoneDepot1.setPreferredSize(new java.awt.Dimension(87, 120));

        javax.swing.GroupLayout jZoneDepot1Layout = new javax.swing.GroupLayout(jZoneDepot1);
        jZoneDepot1.setLayout(jZoneDepot1Layout);
        jZoneDepot1Layout.setHorizontalGroup(
            jZoneDepot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        jZoneDepot1Layout.setVerticalGroup(
            jZoneDepot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 9, 20, 9);
        jPanel1.add(jZoneDepot1, gridBagConstraints);

        jZoneDepot2.setPreferredSize(new java.awt.Dimension(87, 120));

        javax.swing.GroupLayout jZoneDepot2Layout = new javax.swing.GroupLayout(jZoneDepot2);
        jZoneDepot2.setLayout(jZoneDepot2Layout);
        jZoneDepot2Layout.setHorizontalGroup(
            jZoneDepot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        jZoneDepot2Layout.setVerticalGroup(
            jZoneDepot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 9, 20, 9);
        jPanel1.add(jZoneDepot2, gridBagConstraints);

        jZoneDepot3.setPreferredSize(new java.awt.Dimension(87, 120));

        javax.swing.GroupLayout jZoneDepot3Layout = new javax.swing.GroupLayout(jZoneDepot3);
        jZoneDepot3.setLayout(jZoneDepot3Layout);
        jZoneDepot3Layout.setHorizontalGroup(
            jZoneDepot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        jZoneDepot3Layout.setVerticalGroup(
            jZoneDepot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 9, 20, 9);
        jPanel1.add(jZoneDepot3, gridBagConstraints);

        jZoneDepot4.setPreferredSize(new java.awt.Dimension(87, 120));

        javax.swing.GroupLayout jZoneDepot4Layout = new javax.swing.GroupLayout(jZoneDepot4);
        jZoneDepot4.setLayout(jZoneDepot4Layout);
        jZoneDepot4Layout.setHorizontalGroup(
            jZoneDepot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        jZoneDepot4Layout.setVerticalGroup(
            jZoneDepot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 9, 20, 9);
        jPanel1.add(jZoneDepot4, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private boundary.components.JZoneDepot jZoneDepot1;
    private boundary.components.JZoneDepot jZoneDepot2;
    private boundary.components.JZoneDepot jZoneDepot3;
    private boundary.components.JZoneDepot jZoneDepot4;
    // End of variables declaration//GEN-END:variables
}
