/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.components;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import noyau.BasicCategorie;

/**
 *
 * @author yannf
 */
public class JZoneDepot extends javax.swing.JPanel {
    private Image carte;
    private String nomPirate;
    private BasicCategorie type;

    
    /**
     * Creates new form JZoneDepot
     */
    public JZoneDepot() {
        initComponents();
        setOpaque(false);
        setDoubleBuffered(true);
    }

    public void createZoneDepot(String nomPirate, BasicCategorie type){
        this.nomPirate = nomPirate;
        this.type = type;
    }
    
    public boolean ajouterCarte (JCarte carte, String pirate){
        if (!nomPirate.equals(pirate) || carte.getCategorie() != type){ 
            System.out.println("NomPirate : " + nomPirate +" \t pirate : " + pirate);
            return false;
        }
        this.carte = carte.getImage();
        return true;
    }
    
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        if(carte != null){
            g2d.drawImage(carte, 0,0, getWidth(), getHeight(), this);
        } else{
            Color shadowColor = new Color(0, 0, 0, 100);
            g2d.setColor(shadowColor);
            int w = getWidth();
            int h = getHeight();
            g2d.fillRoundRect(0, 0, w, h, w/12, h/12);


            if (type!= null){
            
                //TODO ADD titre
                g2d.setColor(Color.WHITE);
                String title = type.toString() + " - " + nomPirate; // "\n" doesn't create line break in drawString

                Font titleFont = new Font("Segoe UI", Font.PLAIN, 12); // "Segeo UI" corrected to "Segoe UI"
                g2d.setFont(titleFont);
                FontMetrics fm = g2d.getFontMetrics();
                int textWidth = fm.stringWidth(title);
                int x = (getWidth() - textWidth) / 2;
                int y = (getHeight() / 4); // arbitrary Y position for title
                g2d.drawString(title, x, y);
            }
        }    
        

        g2d.dispose();
    }
    
    @Override
    public String toString(){
        return nomPirate + ", " + type.toString();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
