/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.components;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import noyau.CategorieCarte;

/**
 *
 * @author yannf
 */
public class JZoneDepot extends javax.swing.JPanel {
    private Image carte;
    private String nomPirate;
    private CategorieCarte type;
    
    /**
     * Creates new form JZoneDepot
     */
    public JZoneDepot() {
        initComponents();
    }

    public void createZoneDepot(String nomPirate, CategorieCarte type){
        this.nomPirate = nomPirate;
        this.type = type;
    }
    
    public boolean ajouterCarte (JCarte carte, String pirate){
        this.carte = carte.getImage();
        return true;
    }
    
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        if(carte != null){
            g2d.drawImage(carte, 0,0, getWidth(), getHeight(), this);
        } else {
            g2d.setColor(Color.red);
            g2d.drawRect(0, 0, getWidth(), getHeight());
        }
        
        g2d.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
