/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/*author*/
package boundary.components;

import javax.swing.*;
import projetpirates.ProjetPirates;

/**
 *
 * @author hai , leo
 */
public class VictoryScreen extends JPanel {

	private static final long serialVersionUID = 1L;
	
    /**
     * Creates new form VictoryScreen
     */
    private String filenameVictory;
    private Image fieldImage;
    private final JFrame parentFrame;
    private String winner;
    public VictoryScreen(String winner,JFrame parent) {
    	this.winner = winner;
    	this.parentFrame= parent;
        if (winner.equals("Jake Gibbs")) {
        	filenameVictory = "IconP1.png";
        }else {
        	filenameVictory = "IconP2.png";
        }
        try {
        	fieldImage = ImageIO.read(getClass().getResource("/pirates_background(1).png"));
        }catch (IOException e){
        	e.printStackTrace();
        }
		initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	boundary.components.JButtonCustom Rerun = new boundary.components.JButtonCustom();
    	boundary.components.JButtonCustom jButtonCustom4 = new boundary.components.JButtonCustom();
    	boundary.components.JPirateIcon pirateVictoire = new boundary.components.JPirateIcon();
        boundary.components.DrawVictoryPanel drawVictoryPanel1 = new boundary.components.DrawVictoryPanel();
        pirateVictoire.setNomPirate(winner);
		pirateVictoire.setImage(filenameVictory);
		Rerun.setImage("B");
		jButtonCustom4.setImage("B");
		

        Rerun.setText("Main Menu");
        Rerun.addMouseListener(new java.awt.event.MouseAdapter() {
        	@Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RerunMouseClicked();
            }
        });

        jButtonCustom4.setText("Exit");
        jButtonCustom4.addMouseListener(new java.awt.event.MouseAdapter() {
        	@Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCustom4MouseClicked();
            }
        });

        javax.swing.GroupLayout jPanelWithBackground2Layout = new javax.swing.GroupLayout(pirateVictoire);
        pirateVictoire.setLayout(jPanelWithBackground2Layout);
        jPanelWithBackground2Layout.setHorizontalGroup(
            jPanelWithBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );
        jPanelWithBackground2Layout.setVerticalGroup(
            jPanelWithBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout drawVictoryPanel1Layout = new javax.swing.GroupLayout(drawVictoryPanel1);
        drawVictoryPanel1.setLayout(drawVictoryPanel1Layout);
        drawVictoryPanel1Layout.setHorizontalGroup(
            drawVictoryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        drawVictoryPanel1Layout.setVerticalGroup(
            drawVictoryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pirateVictoire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Rerun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drawVictoryPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pirateVictoire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drawVictoryPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rerun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void RerunMouseClicked() {//GEN-FIRST:event_RerunMouseClicked
    	// 1) Close the JDialog (or whatever top‐level Window) that holds this panel:
        Window popup = SwingUtilities.getWindowAncestor(this);
        if (popup != null) {
            popup.dispose();
        }

        // 2) Close the original game JFrame you passed in:
        if (parentFrame != null) {
            parentFrame.dispose();
        }

        new javax.swing.Timer(300, e -> {
            ((javax.swing.Timer)e.getSource()).stop();
            ProjetPirates.main(null);
        }).start();
    }//GEN-LAST:event_RerunMouseClicked

    private void jButtonCustom4MouseClicked() {//GEN-FIRST:event_jButtonCustom4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButtonCustom4MouseClicked
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (fieldImage != null) {
            // stretch to fill the panel, or supply your own width/height
            g.drawImage(fieldImage, 0, 0, getWidth(), getHeight(), this);
        }
    }

}
