/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary;

import java.io.File;
import java.io.IOException;
import java.awt.Image;
import javax.imageio.ImageIO;
import javax.swing.JPanel;

/**
 *
 * @author yannf
 */
public class FrameJeu extends javax.swing.JFrame {

    /**
     * Creates new form FrameJeu
     */
    public FrameJeu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelParent = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        menuPanelBackground = new boundary.components.JPanelWithBackground();
        titleMenu = new javax.swing.JLabel();
        startButton = new boundary.components.JButtonCustom();
        optionButton = new boundary.components.JButtonCustom();
        quitButton = new boundary.components.JButtonCustom();
        plateauPanel = new javax.swing.JPanel();
        plateau1 = new boundary.Plateau();
        optionPanel = new javax.swing.JPanel();
        optionPanelBackground = new boundary.components.JPanelWithBackground();
        optionPanelRound = new boundary.components.JPanelRound();
        resolutionLabel = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        volumeLabel = new javax.swing.JLabel();
        resolutionNbLabel = new javax.swing.JLabel();
        volumeLabel1 = new javax.swing.JLabel();
        rightArrowRes = new boundary.components.JButtonCustom();
        leftArrowRes = new boundary.components.JButtonCustom();
        fullscreenCheckBox = new javax.swing.JCheckBox();
        titleOption = new javax.swing.JLabel();
        menuBoutonOp = new boundary.components.JButtonCustom();
        try{
            menuBoutonOp.setImage();
        }catch (IOException e){
            System.out.print("Button Icon Not Found");
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Argonautes");
        setFont(new java.awt.Font("Windlass", 0, 10)); // NOI18N
        setIconImage(getIcon("Icon23.png"));
        setResizable(false);

        jPanelParent.setLayout(new java.awt.CardLayout());

        menuPanel.setToolTipText("");

        try{
            menuPanelBackground.setImage("pirates_background.png");
        }catch (IOException e) {
            String userDirectory = new File("").getAbsolutePath();
            System.out.print("Background not found"); // or handle the error
        }
        menuPanelBackground.repaint();

        titleMenu.setFont(new java.awt.Font("Windlass", 0, 48)); // NOI18N
        titleMenu.setText("Argonautes");

        startButton.setText("Start");
        startButton.setFont(new java.awt.Font("Windlass", 0, 14)); // NOI18N
        try{
            startButton.setImage();
        }catch (IOException e){
            System.out.print("Button Icon Not Found");
        }
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        optionButton.setText("Option");
        optionButton.setFont(new java.awt.Font("Windlass", 0, 14)); // NOI18N
        try{
            optionButton.setImage();
        }catch (IOException e){
            System.out.print("Button Icon Not Found");
        }
        optionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.setFont(new java.awt.Font("Windlass", 0, 14)); // NOI18N
        try{
            quitButton.setImage();
        }catch (IOException e){
            System.out.print("Button Icon Not Found");
        }
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelBackgroundLayout = new javax.swing.GroupLayout(menuPanelBackground);
        menuPanelBackground.setLayout(menuPanelBackgroundLayout);
        menuPanelBackgroundLayout.setHorizontalGroup(
                menuPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelBackgroundLayout.createSequentialGroup()
                                .addContainerGap(362, Short.MAX_VALUE)
                                .addGroup(menuPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(titleMenu)
                                        .addComponent(optionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45))
        );
        menuPanelBackgroundLayout.setVerticalGroup(
                menuPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menuPanelBackgroundLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(titleMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(optionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(204, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
                menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menuPanelBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
                menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menuPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelParent.add(menuPanel, "card2");

        javax.swing.GroupLayout plateauPanelLayout = new javax.swing.GroupLayout(plateauPanel);
        plateauPanel.setLayout(plateauPanelLayout);
        plateauPanelLayout.setHorizontalGroup(
                plateauPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plateauPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(plateau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        plateauPanelLayout.setVerticalGroup(
                plateauPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(plateauPanelLayout.createSequentialGroup()
                                .addComponent(plateau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanelParent.add(plateauPanel, "card3");

        optionPanelBackground.setPreferredSize(new java.awt.Dimension(720, 480));
        try{
            optionPanelBackground.setImage("pirates_background.png");
        }catch (IOException e) {
            String userDirectory = new File("").getAbsolutePath();
            System.out.print("Background not found"); // or handle the error
        }
        menuPanelBackground.repaint();

        resolutionLabel.setFont(new java.awt.Font("Windlass", 0, 14)); // NOI18N
        resolutionLabel.setText("Resolution :");

        volumeLabel.setFont(new java.awt.Font("Windlass", 0, 14)); // NOI18N
        volumeLabel.setText("Volume :");

        resolutionNbLabel.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        resolutionNbLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resolutionNbLabel.setText("720x480");

        volumeLabel1.setFont(new java.awt.Font("Windlass", 0, 14)); // NOI18N
        volumeLabel1.setText("Fullscreen :");

        rightArrowRes.setText(">");
        rightArrowRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightArrowResActionPerformed(evt);
            }
        });

        leftArrowRes.setText("<");
        leftArrowRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftArrowResActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionPanelRoundLayout = new javax.swing.GroupLayout(optionPanelRound);
        optionPanelRound.setLayout(optionPanelRoundLayout);
        optionPanelRoundLayout.setHorizontalGroup(
                optionPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(optionPanelRoundLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(optionPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(optionPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(optionPanelRoundLayout.createSequentialGroup()
                                                        .addComponent(volumeLabel)
                                                        .addGap(63, 63, 63))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelRoundLayout.createSequentialGroup()
                                                        .addComponent(resolutionLabel)
                                                        .addGap(38, 38, 38)))
                                        .addGroup(optionPanelRoundLayout.createSequentialGroup()
                                                .addComponent(volumeLabel1)
                                                .addGap(39, 39, 39)))
                                .addGroup(optionPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(optionPanelRoundLayout.createSequentialGroup()
                                                .addComponent(leftArrowRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(resolutionNbLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(35, 35, 35)
                                                .addComponent(rightArrowRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jSlider1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fullscreenCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(156, Short.MAX_VALUE))
        );
        optionPanelRoundLayout.setVerticalGroup(
                optionPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(optionPanelRoundLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(optionPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(resolutionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(resolutionNbLabel)
                                        .addComponent(rightArrowRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(leftArrowRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(optionPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(volumeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(optionPanelRoundLayout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(fullscreenCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(optionPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(volumeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(95, Short.MAX_VALUE))
        );

        titleOption.setFont(new java.awt.Font("Windlass", 0, 48)); // NOI18N
        titleOption.setText("Argonautes");

        menuBoutonOp.setText("Retrun Menu");
        menuBoutonOp.setFont(new java.awt.Font("Windlass", 0, 14)); // NOI18N
        menuBoutonOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBoutonOpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionPanelBackgroundLayout = new javax.swing.GroupLayout(optionPanelBackground);
        optionPanelBackground.setLayout(optionPanelBackgroundLayout);
        optionPanelBackgroundLayout.setHorizontalGroup(
                optionPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(optionPanelBackgroundLayout.createSequentialGroup()
                                .addGroup(optionPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(optionPanelBackgroundLayout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(optionPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(titleOption)
                                                        .addComponent(menuBoutonOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(optionPanelBackgroundLayout.createSequentialGroup()
                                                .addGap(89, 89, 89)
                                                .addComponent(optionPanelRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(109, Short.MAX_VALUE))
        );
        optionPanelBackgroundLayout.setVerticalGroup(
                optionPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(optionPanelBackgroundLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(titleOption, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(optionPanelRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(menuBoutonOp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
                optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(optionPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        optionPanelLayout.setVerticalGroup(
                optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(optionPanelLayout.createSequentialGroup()
                                .addComponent(optionPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelParent.add(optionPanel, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 720, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 486, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBoutonOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBoutonOpActionPerformed
        switchPanel(menuPanel);
    }//GEN-LAST:event_menuBoutonOpActionPerformed

    private void leftArrowResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftArrowResActionPerformed
        currentRes = (currentRes - 1)%resolution.length;
        if (currentRes <0){ currentRes = resolution.length -1 ;}
        resolutionNbLabel.setText(resolution[currentRes]);

        String[] res = (resolution[currentRes]).split("[x]");
        setSize(Integer.parseInt(res[0]), Integer.parseInt(res[1]));
    }//GEN-LAST:event_leftArrowResActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        switchPanel(plateauPanel);
    }//GEN-LAST:event_startButtonActionPerformed

    private void optionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionButtonActionPerformed
        switchPanel(optionPanel);
    }//GEN-LAST:event_optionButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_quitButtonActionPerformed

    private void rightArrowResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightArrowResActionPerformed
        currentRes = (currentRes + 1)%resolution.length;
        resolutionNbLabel.setText(resolution[currentRes]);

        String[] res = (resolution[currentRes]).split("[x]");
        setSize(Integer.parseInt(res[0]), Integer.parseInt(res[1]));
    }//GEN-LAST:event_rightArrowResActionPerformed

    private void switchPanel (JPanel p){
        jPanelParent.removeAll();
        jPanelParent.add(p);
        repaint();
        revalidate();
    }

    private Image getIcon(String filename){
        Image res = null;
        try{
            res  = ImageIO.read(new File("src/main/java/com/ilu4/jeuxpirate/boundary/ressources/" + filename));
        }catch(IOException e){
            System.out.print("Icon not found");
        }
        return res;
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameJeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox fullscreenCheckBox;
    private javax.swing.JPanel jPanelParent;
    private javax.swing.JSlider jSlider1;
    private boundary.components.JButtonCustom leftArrowRes;
    private boundary.components.JButtonCustom menuBoutonOp;
    private javax.swing.JPanel menuPanel;
    private boundary.components.JPanelWithBackground menuPanelBackground;
    private boundary.components.JButtonCustom optionButton;
    private javax.swing.JPanel optionPanel;
    private boundary.components.JPanelWithBackground optionPanelBackground;
    private boundary.components.JPanelRound optionPanelRound;
    private boundary.Plateau plateau1;
    private javax.swing.JPanel plateauPanel;
    private boundary.components.JButtonCustom quitButton;
    private javax.swing.JLabel resolutionLabel;
    private javax.swing.JLabel resolutionNbLabel;
    private boundary.components.JButtonCustom rightArrowRes;
    private boundary.components.JButtonCustom startButton;
    private javax.swing.JLabel titleMenu;
    private javax.swing.JLabel titleOption;
    private javax.swing.JLabel volumeLabel;
    private javax.swing.JLabel volumeLabel1;
    // End of variables declaration//GEN-END:variables
    private final String[] resolution ={"720x480", "1280x720", "1920x1080"};
    private int currentRes = 0;
}
