/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary;

import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Collections;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.FloatControl;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JPanel;

/**
 *
 * @author yannf et vincent
 */
public class FrameJeu extends javax.swing.JFrame {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private final BoundaryJeu boundaryJeu;
    /**
     * Creates new form FrameJeu
     * @param boundaryJeu
     * @param fullScreen
     */
    public FrameJeu(BoundaryJeu boundaryJeu, boolean fullScreen) {
        this.boundaryJeu = boundaryJeu;
        if (fullScreen) {
            setUndecorated(true);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelParent = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        menuPanelBackground = new boundary.components.JPanelWithBackground();
        titleBackground = new boundary.components.JPanelWithBackground();
        BottomPanel = new javax.swing.JPanel();
        MenuButtonPanel = new javax.swing.JPanel();
        startButton = new boundary.components.JButtonCustom();
        startButton.setImage("B");
        optionButton = new boundary.components.JButtonCustom();
        optionButton.setImage("B");
        quitButton = new boundary.components.JButtonCustom();
        quitButton.setImage("B");
        optionPanel = new javax.swing.JPanel();
        optionPanelBackground = new boundary.components.JPanelWithBackground();
        titleBackground1 = new boundary.components.JPanelWithBackground();
        optionPanelRound = new boundary.components.JPanelRound();
        resolutionLabel = new javax.swing.JLabel();
        fullScreenLabel = new javax.swing.JLabel();
        volumeLabel = new javax.swing.JLabel();
        fullScreenCheckBox = new javax.swing.JCheckBox();
        volumeSlider = new javax.swing.JSlider();
        leftArrowRes = new boundary.components.JButtonCustom();
        rightArrowRes = new boundary.components.JButtonCustom();
        resolutionNbLabel = new javax.swing.JLabel();
        volumeValueLabel = new javax.swing.JLabel();
        menuBoutonOp = new boundary.components.JButtonCustom();
        plateauPanel = new javax.swing.JPanel();
        plateau1 = new boundary.Plateau();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Argonautes : New Horizons");
        setIconImage(
            getIcon("Icon23.png")
        );
        setMinimumSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
        	@Override
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelParent.setOpaque(false);
        jPanelParent.setPreferredSize(new java.awt.Dimension(720, 480));
        jPanelParent.setLayout(new java.awt.CardLayout());

        menuPanel.setAutoscrolls(true);
        menuPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuPanel.setOpaque(false);
        menuPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
        	@Override
            public void componentShown(java.awt.event.ComponentEvent evt) {
                menuPanelComponentShown(evt);
            }
        });

        menuPanelBackground.setImage("pirates_background(4).png");
        java.awt.GridBagLayout menuPanelBackgroundLayout1 = new java.awt.GridBagLayout();
        menuPanelBackgroundLayout1.columnWeights = new double[] {0.0, 0.5};
        menuPanelBackgroundLayout1.rowWeights = new double[] {0.0, 0.5};
        menuPanelBackground.setLayout(menuPanelBackgroundLayout1);

        titleBackground.setMinimumSize(new java.awt.Dimension(325, 56));
        titleBackground.setOpaque(false);
        titleBackground.setPreferredSize(new java.awt.Dimension(325, 56));
        titleBackground.setImage("Title2.png");

        javax.swing.GroupLayout titleBackgroundLayout = new javax.swing.GroupLayout(titleBackground);
        titleBackground.setLayout(titleBackgroundLayout);
        titleBackgroundLayout.setHorizontalGroup(
            titleBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        titleBackgroundLayout.setVerticalGroup(
            titleBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.35;
        gridBagConstraints.weighty = 0.35;
        gridBagConstraints.insets = new java.awt.Insets(30, 100, 0, 100);
        menuPanelBackground.add(titleBackground, gridBagConstraints);

        BottomPanel.setAlignmentX(0.0F);
        BottomPanel.setAlignmentY(0.0F);
        BottomPanel.setMinimumSize(new java.awt.Dimension(620, 363));
        BottomPanel.setOpaque(false);
        BottomPanel.setLayout(new java.awt.GridBagLayout());

        MenuButtonPanel.setOpaque(false);

        startButton.setBackground(new java.awt.Color(0, 51, 102));
        startButton.setForeground(new java.awt.Color(255, 255, 255));
        startButton.setText("Start");
        startButton.setFont(new java.awt.Font("Windlass", 0, 14)); // NOI18N
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        optionButton.setBackground(new java.awt.Color(0, 51, 102));
        optionButton.setForeground(new java.awt.Color(255, 255, 255));
        optionButton.setText("Option");
        optionButton.setFont(new java.awt.Font("Windlass", 0, 14)); // NOI18N
        optionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionButtonActionPerformed(evt);
            }
        });

        quitButton.setBackground(new java.awt.Color(0, 51, 102));
        quitButton.setForeground(new java.awt.Color(255, 255, 255));
        quitButton.setText("Quit");
        quitButton.setFont(new java.awt.Font("Windlass", 0, 14)); // NOI18N
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuButtonPanelLayout = new javax.swing.GroupLayout(MenuButtonPanel);
        MenuButtonPanel.setLayout(MenuButtonPanelLayout);
        MenuButtonPanelLayout.setHorizontalGroup(
            MenuButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(MenuButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MenuButtonPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(MenuButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(optionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        MenuButtonPanelLayout.setVerticalGroup(
            MenuButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
            .addGroup(MenuButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MenuButtonPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(24, 24, 24)
                    .addComponent(optionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(24, 24, 24)
                    .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weightx = 1.0;
        BottomPanel.add(MenuButtonPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 30, 50);
        menuPanelBackground.add(BottomPanel, gridBagConstraints);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelParent.add(menuPanel, "card2");

        optionPanel.setBackground(new java.awt.Color(51, 51, 255));
        optionPanel.setPreferredSize(new java.awt.Dimension(720, 480));
        optionPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
        	@Override
            public void componentShown(java.awt.event.ComponentEvent evt) {
                optionPanelComponentShown(evt);
            }
        });
        optionPanel.addKeyListener(new java.awt.event.KeyAdapter() {
        	@Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                optionPanelKeyReleased(evt);
            }
        });

        optionPanelBackground.setImage("pirates_background(4).png");
        java.awt.GridBagLayout optionPanelBackgroundLayout1 = new java.awt.GridBagLayout();
        optionPanelBackgroundLayout1.columnWeights = new double[] {0.0, 0.5};
        optionPanelBackgroundLayout1.rowWeights = new double[] {0.0, 0.5};
        optionPanelBackground.setLayout(optionPanelBackgroundLayout1);

        titleBackground1.setAlignmentX(0.0F);
        titleBackground1.setAlignmentY(0.0F);
        titleBackground1.setMinimumSize(new java.awt.Dimension(325, 56));
        titleBackground1.setOpaque(false);
        titleBackground1.setPreferredSize(new java.awt.Dimension(325, 56));
        titleBackground1.setImage("Title2.png");

        javax.swing.GroupLayout titleBackground1Layout = new javax.swing.GroupLayout(titleBackground1);
        titleBackground1.setLayout(titleBackground1Layout);
        titleBackground1Layout.setHorizontalGroup(
            titleBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );
        titleBackground1Layout.setVerticalGroup(
            titleBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 0, 50);
        optionPanelBackground.add(titleBackground1, gridBagConstraints);

        optionPanelRound.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resolutionLabel.setFont(new java.awt.Font("Windlass", 0, 18)); // NOI18N
        resolutionLabel.setText("Resolution : ");
        optionPanelRound.add(resolutionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        fullScreenLabel.setFont(new java.awt.Font("Windlass", 0, 18)); // NOI18N
        fullScreenLabel.setText("FullScreen : ");
        optionPanelRound.add(fullScreenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        volumeLabel.setFont(new java.awt.Font("Windlass", 0, 18)); // NOI18N
        volumeLabel.setText("Volume : ");
        optionPanelRound.add(volumeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        fullScreenCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullScreenCheckBoxActionPerformed(evt);
            }
        });
        optionPanelRound.add(fullScreenCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        volumeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                volumeSliderStateChanged(evt);
            }
        });
        optionPanelRound.add(volumeSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        leftArrowRes.setPreferredSize(new java.awt.Dimension(20, 20));
        leftArrowRes.setImage("L");
        leftArrowRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftArrowResActionPerformed(evt);
            }
        });
        optionPanelRound.add(leftArrowRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        rightArrowRes.setPreferredSize(new java.awt.Dimension(20, 20));
        rightArrowRes.setImage("R");
        rightArrowRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightArrowResActionPerformed(evt);
            }
        });
        optionPanelRound.add(rightArrowRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        resolutionNbLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resolutionNbLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resolutionNbLabel.setText("720x480");
        optionPanelRound.add(resolutionNbLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 85, -1));

        volumeValueLabel.setBackground(new java.awt.Color(0, 0, 0));
        volumeValueLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        volumeValueLabel.setText("50%");
        optionPanelRound.add(volumeValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 37, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(25, 50, 25, 50);
        optionPanelBackground.add(optionPanelRound, gridBagConstraints);

        menuBoutonOp.setBackground(new java.awt.Color(0, 51, 102));
        menuBoutonOp.setForeground(new java.awt.Color(255, 255, 255));
        menuBoutonOp.setText("Return Menu");
        menuBoutonOp.setFont(new java.awt.Font("Windlass", 0, 14)); // NOI18N
        menuBoutonOp.setImage("B");
        menuBoutonOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBoutonOpActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 40, 50);
        optionPanelBackground.add(menuBoutonOp, gridBagConstraints);

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelParent.add(optionPanel, "card3");

        plateauPanel.setMinimumSize(new java.awt.Dimension(720, 480));
        plateauPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                plateauPanelComponentShown(evt);
            }
        });
        plateauPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                plateauPanelKeyPressed(evt);
            }
        });
        plateauPanel.setLayout(new java.awt.BorderLayout());
        plateauPanel.add(plateau1, java.awt.BorderLayout.CENTER);

        jPanelParent.add(plateauPanel, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBoutonOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBoutonOpActionPerformed
        switchPanel(menuPanel);
        optionPanel.setVisible(false);
    }//GEN-LAST:event_menuBoutonOpActionPerformed

    private void leftArrowResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftArrowResActionPerformed
        currentRes = (currentRes - 1)%resolution.length;
        if (currentRes <0){ currentRes = resolution.length -1 ;}
        resolutionNbLabel.setText(resolution[currentRes]);

        String[] res = (resolution[currentRes]).split("[x]");
        setSize(Integer.parseInt(res[0]), Integer.parseInt(res[1]));
    }//GEN-LAST:event_leftArrowResActionPerformed

    private void rightArrowResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightArrowResActionPerformed
        currentRes = (currentRes + 1)%resolution.length;
        resolutionNbLabel.setText(resolution[currentRes]);

        String[] res = (resolution[currentRes]).split("[x]");
        setSize(Integer.parseInt(res[0]), Integer.parseInt(res[1]));
    }//GEN-LAST:event_rightArrowResActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustom1ActionPerformed
        switchPanel(plateauPanel);
        menuPanel.setVisible(false);
        
        plateauPanel.setSize(getWidth(), getHeight());
        plateau1.setSize(getWidth(), getHeight());

        plateau1.setBoundaryJeu(boundaryJeu);
    }//GEN-LAST:event_jButtonCustom1ActionPerformed

    private void optionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustom2ActionPerformed
        switchPanel(optionPanel);
        menuPanel.setVisible(false);
    }//GEN-LAST:event_jButtonCustom2ActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustom3ActionPerformed
        stopMusic();
        dispose();
    }//GEN-LAST:event_jButtonCustom3ActionPerformed

    private void fullScreenCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullScreenCheckBoxActionPerformed
        FrameJeu newFrame = new FrameJeu(boundaryJeu, fullScreenCheckBox.isSelected());
        this.dispose();
        fullScreenOptionEnable(newFrame, !fullScreenCheckBox.isSelected());
        newFrame.fullScreenCheckBox.setSelected(fullScreenCheckBox.isSelected());
        
        if (fullScreenCheckBox.isSelected()) {
            newFrame.setExtendedState(MAXIMIZED_BOTH);
        }

        newFrame.openOptionsPanel();
        newFrame.setVisible(true);
    }//GEN-LAST:event_fullScreenCheckBoxActionPerformed
    
    
    private void plateauPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_plateauPanelKeyPressed
        Component focused = KeyboardFocusManager.getCurrentKeyboardFocusManager().getFocusOwner();
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE && plateauPanel.equals(focused)){
            switchPanel(menuPanel);
            plateauPanel.setVisible(false);
        }
    }//GEN-LAST:event_plateauPanelKeyPressed

    private void plateauPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_plateauPanelComponentShown
        plateauPanel.requestFocusInWindow();
    }//GEN-LAST:event_plateauPanelComponentShown

    private void menuPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_menuPanelComponentShown
        menuPanel.requestFocusInWindow();
    }//GEN-LAST:event_menuPanelComponentShown

    private void optionPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_optionPanelComponentShown
       optionPanel.requestFocusInWindow();
    }//GEN-LAST:event_optionPanelComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Uniquement des fichiers audio .wav !
        // Ajoutez le fichier nommé SongX.wav avec X = nb_musics +1
        // Pensez à incrémenter le nombre de musique
        int nb_musics = 4;
        ArrayList<String> playlist = new ArrayList<>();
        for (int i = 1; i <= nb_musics; i++) {
            playlist.add("src/main/resources/Song" + i + ".wav");
        }
        Collections.shuffle(playlist);
        
        playMusics(playlist);
    }//GEN-LAST:event_formWindowOpened

    private void volumeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volumeSliderStateChanged
        int newVolume = volumeSlider.getValue();
        volumeValueLabel.setText(newVolume + "%");
        volume = newVolume / 100;
        setVolume(volume);
    }//GEN-LAST:event_volumeSliderStateChanged

    private void optionPanelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_optionPanelKeyReleased
        Component focused = KeyboardFocusManager.getCurrentKeyboardFocusManager().getFocusOwner();
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE && optionPanel.equals(focused)){
            switchPanel(menuPanel);
            optionPanel.setVisible(false);
        }
    }//GEN-LAST:event_optionPanelKeyReleased

    private void switchPanel (JPanel p){
        jPanelParent.removeAll();
        jPanelParent.add(p);
        p.setVisible(true);
        p.setFocusable(true);
        p.setEnabled(true);
        p.setRequestFocusEnabled(true);
        repaint();
        revalidate();
    }

    private Image getIcon(String filename){
        Image res = null;
        try{
            /*ImageIcon icon = new ImageIcon(getClass().getResource(fileName));
            res = icon.getImage();*/
            res  = ImageIO.read(new File("src/main/resources/" + filename));
        }catch(IOException e){
            String userDirectory = new File("").getAbsolutePath();
            System.out.print("Icon not found : " + userDirectory + "src/main/resources/" + filename);
        }
        return res;
    }
    
    private void openOptionsPanel() {
        switchPanel(optionPanel);
        optionPanelRound.repaint();
    }
    
    private void fullScreenOptionEnable(FrameJeu frame, boolean bool) {
        frame.leftArrowRes.setEnabled(bool);
        frame.rightArrowRes.setEnabled(bool);
        frame.resolutionLabel.setEnabled(bool);
        frame.resolutionNbLabel.setEnabled(bool);
    }
    
    private void playCurrentTrack() {
        try {
            if (currentIndex >= playlist.size()) {
                currentIndex = 0;
            }

            String filepath = playlist.get(currentIndex);
            File audioFile = new File(filepath);

            if (!audioFile.exists()) {
                System.out.println("Fichier introuvable : " + filepath);
                currentIndex++;
                playCurrentTrack();
                return;
            }

            AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);
            clip = AudioSystem.getClip();
            clip.open(audioStream);
            setVolume(volume);
            clip.start();

            // Quand le son est fini, passer au suivant
            clip.addLineListener(event -> {
                if (event.getType() == LineEvent.Type.STOP) {
                    clip.close();
                    currentIndex++;
                    playCurrentTrack();
                }
            });

        } catch (IOException | LineUnavailableException | UnsupportedAudioFileException e) {
            System.out.println("Musique non trouvé.");
        }
    }
    
    public void playMusics(ArrayList<String> filepaths) {
        if (filepaths == null || filepaths.isEmpty()) {
            System.out.println("La liste de lecture est vide.");
            return;
        }
        this.playlist = filepaths;
        this.currentIndex = 0;
        playCurrentTrack();
    }
    
    public void stopMusic() {
        if (clip != null && clip.isRunning()) {
            clip.stop();
        }
    }
    
    // Volume doit être compris entre 0 et 1
    public void setVolume(float volume) {
        if (clip != null && clip.isControlSupported(FloatControl.Type.MASTER_GAIN)) {
            FloatControl gainControl = (FloatControl) clip.getControl(FloatControl.Type.MASTER_GAIN);
            float range = gainControl.getMaximum() - gainControl.getMinimum();
            float gain = (range * volume) + gainControl.getMinimum();
            gainControl.setValue(gain);
        }
    }
    
    public Plateau getPlateau(){
        return plateau1;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrameJeu(null, false).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JPanel MenuButtonPanel;
    private javax.swing.JCheckBox fullScreenCheckBox;
    private javax.swing.JLabel fullScreenLabel;
    private javax.swing.JPanel jPanelParent;
    private boundary.components.JButtonCustom leftArrowRes;
    private boundary.components.JButtonCustom menuBoutonOp;
    private javax.swing.JPanel menuPanel;
    private boundary.components.JPanelWithBackground menuPanelBackground;
    private boundary.components.JButtonCustom optionButton;
    private javax.swing.JPanel optionPanel;
    private boundary.components.JPanelWithBackground optionPanelBackground;
    private boundary.components.JPanelRound optionPanelRound;
    private boundary.Plateau plateau1;
    private javax.swing.JPanel plateauPanel;
    private boundary.components.JButtonCustom quitButton;
    private javax.swing.JLabel resolutionLabel;
    private javax.swing.JLabel resolutionNbLabel;
    private boundary.components.JButtonCustom rightArrowRes;
    private boundary.components.JButtonCustom startButton;
    private boundary.components.JPanelWithBackground titleBackground;
    private boundary.components.JPanelWithBackground titleBackground1;
    private javax.swing.JLabel volumeLabel;
    private javax.swing.JSlider volumeSlider;
    private javax.swing.JLabel volumeValueLabel;
    // End of variables declaration//GEN-END:variables

    private final String[] resolution ={"720x480", "1280x720", "1920x1080"};
    private int currentRes = 0;
    private Clip clip;
    private float volume = 0.5f; // Volume entre 0 et 1
    private ArrayList<String> playlist = new ArrayList<>();
    private int currentIndex = 0;
}
