/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary;

import noyau.GestionnaireCartes;
import boundary.components.JCarte;
import boundary.components.JPointDeVie;
import boundary.components.JZoneInteraction;

import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author yannf
 */
public class Plateau extends javax.swing.JPanel {
    private JZoneInteraction zoneInteraction = null;
    private JCarte carte;
    private GestionnaireCartes gestionnaire = new GestionnaireCartes();
    
    private List<JCarte> main1 = new ArrayList<>();
    private List<JCarte> main2 = new ArrayList<>();
    
    /**
     * Creates new form Plateau
     */
    public Plateau() {
        initComponents();

/*        zoneInteraction = zoneInteractionJ2;
        carte = jCarte1;
        jCarte1.changeCardFace();
        gestionnaire.ajouterCarte(carte);
        carte = jCarte2;
        gestionnaire.ajouterCarte(carte);
        gestionnaire.ajouterCarte(carte);
        gestionnaire.ajouterZone(zoneInteractionJ2);*/
        setNbViesRestantes(1, 4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        plateauBackground = new boundary.components.JPanelWithBackground();
        iconP1 = new boundary.components.JPanelWithBackground();
        iconP2 = new boundary.components.JPanelWithBackground();
        infoPanelP1 = new javax.swing.JPanel();
        jPointDeVie6 = new boundary.components.JPointDeVie();
        jPointDeVie7 = new boundary.components.JPointDeVie();
        jPointDeVie8 = new boundary.components.JPointDeVie();
        jPointDeVie9 = new boundary.components.JPointDeVie();
        jPointDeVie0 = new boundary.components.JPointDeVie();
        jaugePopulariteP1 = new boundary.components.JPanelWithBackground();
        jaugePopulariteP1.setImage("Icon12.png");
        infoPanelP2 = new javax.swing.JPanel();
        jPointDeVie = new boundary.components.JPointDeVie();
        jPointDeVie2 = new boundary.components.JPointDeVie();
        jPointDeVie3 = new boundary.components.JPointDeVie();
        jPointDeVie4 = new boundary.components.JPointDeVie();
        jPointDeVie5 = new boundary.components.JPointDeVie();
        jaugePopulariteP2 = new boundary.components.JPanelWithBackground();
        jaugePopulariteP1.setImage("Icon12.png");
        ZoneInteractionCentral = new boundary.components.JZoneInteraction();
        depotPopP1 = new boundary.components.JZoneInteraction();
        depotAttP1 = new boundary.components.JZoneInteraction();
        depotAttP2 = new boundary.components.JZoneInteraction();
        depotPopP2 = new boundary.components.JZoneInteraction();
        jPioche1 = new boundary.components.JPioche();
        jMainJoueur2 = new boundary.components.JMainJoueur();
        jSeparator1 = new javax.swing.JSeparator();
        jMainJoueur1 = new boundary.components.JMainJoueur();

        plateauBackground.setMaximumSize(new java.awt.Dimension(1920, 1080));
        plateauBackground.setMinimumSize(new java.awt.Dimension(720, 480));
        plateauBackground.setName(""); // NOI18N
        plateauBackground.setPreferredSize(new java.awt.Dimension(720, 480));
        plateauBackground.setImage("Plateau.png");
        plateauBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconP1.setBackground(new java.awt.Color(204, 204, 0));
        iconP1.setPreferredSize(new java.awt.Dimension(130, 130));
        iconP1.setImage("IconJ1.png");

        javax.swing.GroupLayout iconP1Layout = new javax.swing.GroupLayout(iconP1);
        iconP1.setLayout(iconP1Layout);
        iconP1Layout.setHorizontalGroup(
            iconP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        iconP1Layout.setVerticalGroup(
            iconP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );

        plateauBackground.add(iconP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 120, 134));

        iconP2.setBackground(new java.awt.Color(204, 204, 0));
        iconP2.setPreferredSize(new java.awt.Dimension(130, 130));
        iconP2.setImage("IconJ2.png");

        javax.swing.GroupLayout iconP2Layout = new javax.swing.GroupLayout(iconP2);
        iconP2.setLayout(iconP2Layout);
        iconP2Layout.setHorizontalGroup(
            iconP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        iconP2Layout.setVerticalGroup(
            iconP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );

        plateauBackground.add(iconP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 13, 120, 134));

        infoPanelP1.setOpaque(false);
        infoPanelP1.setPreferredSize(new java.awt.Dimension(138, 148));
        infoPanelP1.setLayout(new java.awt.GridBagLayout());

        jPointDeVie6.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVie6Layout = new javax.swing.GroupLayout(jPointDeVie6);
        jPointDeVie6.setLayout(jPointDeVie6Layout);
        jPointDeVie6Layout.setHorizontalGroup(
            jPointDeVie6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPointDeVie6Layout.setVerticalGroup(
            jPointDeVie6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        infoPanelP1.add(jPointDeVie6, gridBagConstraints);

        jPointDeVie7.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVie7Layout = new javax.swing.GroupLayout(jPointDeVie7);
        jPointDeVie7.setLayout(jPointDeVie7Layout);
        jPointDeVie7Layout.setHorizontalGroup(
            jPointDeVie7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPointDeVie7Layout.setVerticalGroup(
            jPointDeVie7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        infoPanelP1.add(jPointDeVie7, gridBagConstraints);

        jPointDeVie8.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVie8Layout = new javax.swing.GroupLayout(jPointDeVie8);
        jPointDeVie8.setLayout(jPointDeVie8Layout);
        jPointDeVie8Layout.setHorizontalGroup(
            jPointDeVie8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPointDeVie8Layout.setVerticalGroup(
            jPointDeVie8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        infoPanelP1.add(jPointDeVie8, gridBagConstraints);

        jPointDeVie9.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVie9Layout = new javax.swing.GroupLayout(jPointDeVie9);
        jPointDeVie9.setLayout(jPointDeVie9Layout);
        jPointDeVie9Layout.setHorizontalGroup(
            jPointDeVie9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPointDeVie9Layout.setVerticalGroup(
            jPointDeVie9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        infoPanelP1.add(jPointDeVie9, gridBagConstraints);

        jPointDeVie0.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVie0Layout = new javax.swing.GroupLayout(jPointDeVie0);
        jPointDeVie0.setLayout(jPointDeVie0Layout);
        jPointDeVie0Layout.setHorizontalGroup(
            jPointDeVie0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPointDeVie0Layout.setVerticalGroup(
            jPointDeVie0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        infoPanelP1.add(jPointDeVie0, gridBagConstraints);

        jaugePopulariteP1.setOpaque(false);
        jaugePopulariteP1.setPreferredSize(new java.awt.Dimension(119, 119));

        javax.swing.GroupLayout jaugePopulariteP1Layout = new javax.swing.GroupLayout(jaugePopulariteP1);
        jaugePopulariteP1.setLayout(jaugePopulariteP1Layout);
        jaugePopulariteP1Layout.setHorizontalGroup(
            jaugePopulariteP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jaugePopulariteP1Layout.setVerticalGroup(
            jaugePopulariteP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        infoPanelP1.add(jaugePopulariteP1, gridBagConstraints);

        plateauBackground.add(infoPanelP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        infoPanelP2.setBackground(new java.awt.Color(0, 204, 255));
        infoPanelP2.setOpaque(false);
        infoPanelP2.setPreferredSize(new java.awt.Dimension(138, 148));
        infoPanelP2.setLayout(new java.awt.GridBagLayout());

        jPointDeVie.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVieLayout = new javax.swing.GroupLayout(jPointDeVie);
        jPointDeVie.setLayout(jPointDeVieLayout);
        jPointDeVieLayout.setHorizontalGroup(
            jPointDeVieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPointDeVieLayout.setVerticalGroup(
            jPointDeVieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        infoPanelP2.add(jPointDeVie, gridBagConstraints);

        jPointDeVie2.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVie2Layout = new javax.swing.GroupLayout(jPointDeVie2);
        jPointDeVie2.setLayout(jPointDeVie2Layout);
        jPointDeVie2Layout.setHorizontalGroup(
            jPointDeVie2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPointDeVie2Layout.setVerticalGroup(
            jPointDeVie2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        infoPanelP2.add(jPointDeVie2, gridBagConstraints);

        jPointDeVie3.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVie3Layout = new javax.swing.GroupLayout(jPointDeVie3);
        jPointDeVie3.setLayout(jPointDeVie3Layout);
        jPointDeVie3Layout.setHorizontalGroup(
            jPointDeVie3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPointDeVie3Layout.setVerticalGroup(
            jPointDeVie3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        infoPanelP2.add(jPointDeVie3, gridBagConstraints);

        jPointDeVie4.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVie4Layout = new javax.swing.GroupLayout(jPointDeVie4);
        jPointDeVie4.setLayout(jPointDeVie4Layout);
        jPointDeVie4Layout.setHorizontalGroup(
            jPointDeVie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPointDeVie4Layout.setVerticalGroup(
            jPointDeVie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        infoPanelP2.add(jPointDeVie4, gridBagConstraints);

        jPointDeVie5.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPointDeVie5Layout = new javax.swing.GroupLayout(jPointDeVie5);
        jPointDeVie5.setLayout(jPointDeVie5Layout);
        jPointDeVie5Layout.setHorizontalGroup(
            jPointDeVie5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPointDeVie5Layout.setVerticalGroup(
            jPointDeVie5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        infoPanelP2.add(jPointDeVie5, gridBagConstraints);

        jaugePopulariteP2.setOpaque(false);
        jaugePopulariteP2.setPreferredSize(new java.awt.Dimension(119, 119));
        jaugePopulariteP2.setImage("Icon12.png");

        javax.swing.GroupLayout jaugePopulariteP2Layout = new javax.swing.GroupLayout(jaugePopulariteP2);
        jaugePopulariteP2.setLayout(jaugePopulariteP2Layout);
        jaugePopulariteP2Layout.setHorizontalGroup(
            jaugePopulariteP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jaugePopulariteP2Layout.setVerticalGroup(
            jaugePopulariteP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        infoPanelP2.add(jaugePopulariteP2, gridBagConstraints);

        plateauBackground.add(infoPanelP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 130, -1));

        ZoneInteractionCentral.setOpaque(false);
        ZoneInteractionCentral.setLayout(new java.awt.GridBagLayout());

        depotPopP1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        depotPopP1.setMinimumSize(new java.awt.Dimension(84, 117));
        depotPopP1.setPreferredSize(new java.awt.Dimension(84, 117));

        javax.swing.GroupLayout depotPopP1Layout = new javax.swing.GroupLayout(depotPopP1);
        depotPopP1.setLayout(depotPopP1Layout);
        depotPopP1Layout.setHorizontalGroup(
            depotPopP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        depotPopP1Layout.setVerticalGroup(
            depotPopP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        ZoneInteractionCentral.add(depotPopP1, gridBagConstraints);

        depotAttP1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        depotAttP1.setMinimumSize(new java.awt.Dimension(84, 117));
        depotAttP1.setPreferredSize(new java.awt.Dimension(84, 117));

        javax.swing.GroupLayout depotAttP1Layout = new javax.swing.GroupLayout(depotAttP1);
        depotAttP1.setLayout(depotAttP1Layout);
        depotAttP1Layout.setHorizontalGroup(
            depotAttP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        depotAttP1Layout.setVerticalGroup(
            depotAttP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        ZoneInteractionCentral.add(depotAttP1, gridBagConstraints);

        depotAttP2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        depotAttP2.setMinimumSize(new java.awt.Dimension(84, 117));
        depotAttP2.setPreferredSize(new java.awt.Dimension(84, 117));

        javax.swing.GroupLayout depotAttP2Layout = new javax.swing.GroupLayout(depotAttP2);
        depotAttP2.setLayout(depotAttP2Layout);
        depotAttP2Layout.setHorizontalGroup(
            depotAttP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        depotAttP2Layout.setVerticalGroup(
            depotAttP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        ZoneInteractionCentral.add(depotAttP2, gridBagConstraints);

        depotPopP2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        depotPopP2.setMinimumSize(new java.awt.Dimension(84, 117));
        depotPopP2.setPreferredSize(new java.awt.Dimension(84, 117));

        javax.swing.GroupLayout depotPopP2Layout = new javax.swing.GroupLayout(depotPopP2);
        depotPopP2.setLayout(depotPopP2Layout);
        depotPopP2Layout.setHorizontalGroup(
            depotPopP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        depotPopP2Layout.setVerticalGroup(
            depotPopP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        ZoneInteractionCentral.add(depotPopP2, gridBagConstraints);

        plateauBackground.add(ZoneInteractionCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 420, 160));

        jPioche1.setBackground(new java.awt.Color(153, 153, 255));
        jPioche1.setPreferredSize(new java.awt.Dimension(142, 90));
        jPioche1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPioche1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPioche1Layout = new javax.swing.GroupLayout(jPioche1);
        jPioche1.setLayout(jPioche1Layout);
        jPioche1Layout.setHorizontalGroup(
            jPioche1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );
        jPioche1Layout.setVerticalGroup(
            jPioche1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        plateauBackground.add(jPioche1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 195, -1, -1));
        plateauBackground.add(jMainJoueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 420, 160));
        plateauBackground.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 10, 1, 273));
        plateauBackground.add(jMainJoueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 420, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(plateauBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(plateauBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPioche1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPioche1MouseClicked
        if(!jPioche1.isEnabled()) {return;}

        //get carte from noyeau
        //String nomCarte1 = "Popularity";
        List<String> listNomCarte = new ArrayList<>(List.of("Popularity", "Attack"));
        //Create new Card
        //JCarte carte = createCarte(nomCarte);

        /*java.awt.GridBagConstraints newGridBagConstraints;
        newGridBagConstraints = new java.awt.GridBagConstraints();
        newGridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);*/

        int tour = 0; //Tour du joueur 1 nomalement faire un getTour
        if (tour == 0){
            for(String nomCarte : listNomCarte){
                jMainJoueur1.ajouterCarte(nomCarte);
                jMainJoueur1.repaint();
                /*JCarte carte = createCarte(nomCarte);
                gbc.gridx = main1.size();
                main1.add(carte);
                zoneInteractionJ1.add(carte, gbc);
                zoneInteractionJ1.revalidate();
                zoneInteractionJ1.repaint();*/
            }
        } else if (tour == 1){
            for(String nomCarte : listNomCarte){
                jMainJoueur2.ajouterCarte(nomCarte);
                jMainJoueur2.repaint();
                /*gbc.gridx = main2.size();
                main2.add(carte);
                zoneInteractionJ2.add(carte, gbc);
                zoneInteractionJ2.revalidate();
                zoneInteractionJ2.repaint();*/
            }
        }
        jPioche1.setEnabled(false);
    }//GEN-LAST:event_jPioche1MouseClicked

    
    /*private JCarte createCarte(String nomCarte) {
        
        JCarte newCarte = new boundary.components.JCarte();
        newCarte.setMinimumSize(new java.awt.Dimension(84, 117));
        newCarte.setPreferredSize(new java.awt.Dimension(84, 117));
        newCarte.setImage("Card1Front" + nomCarte + ".png");

        javax.swing.GroupLayout newCarteLayout = new javax.swing.GroupLayout(newCarte);
        newCarte.setLayout(newCarteLayout);
        newCarteLayout.setHorizontalGroup(
            newCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );
        newCarteLayout.setVerticalGroup(
            newCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        newCarte.changeCardFace();
        return newCarte;
    }*/
            
            
    public GestionnaireCartes getGestionnaire() {
        return gestionnaire;
    }

/*    public void verifierZoneInteraction(Rectangle boundsCarte) {
        zoneInteractionJ2.verifierCarte(carte);
        Rectangle boundsZone = zoneInteraction.getBounds();
        if (boundsZone.intersects(boundsCarte)) {
            //JOptionPane.showMessageDialog(this, "Carte déposée dans la zone !");    // debuggage
        }
    }*/

    public void setNbViesRestantes(int Pirate , int n) {
        Component[] composants;
        if (Pirate == 1) {
            composants = infoPanelP1.getComponents();
        } else if (Pirate == 2) {
            composants = infoPanelP2.getComponents();
        } else {
            return;
        }
        for (int i = 0; i < composants.length; i++) {
            if (composants[i] instanceof JPointDeVie coeur) {
                coeur.setEtat(i < n); // les premiers pleins, le reste vides
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private boundary.components.JZoneInteraction ZoneInteractionCentral;
    private boundary.components.JZoneInteraction depotAttP1;
    private boundary.components.JZoneInteraction depotAttP2;
    private boundary.components.JZoneInteraction depotPopP1;
    private boundary.components.JZoneInteraction depotPopP2;
    private boundary.components.JPanelWithBackground iconP1;
    private boundary.components.JPanelWithBackground iconP2;
    private boundary.components.JPanelWithBackground iconP3;
    private javax.swing.JPanel infoPanelP1;
    private javax.swing.JPanel infoPanelP2;
    private boundary.components.JMainJoueur jMainJoueur1;
    private boundary.components.JMainJoueur jMainJoueur2;
    private boundary.components.JPioche jPioche1;
    private boundary.components.JPointDeVie jPointDeVie;
    private boundary.components.JPointDeVie jPointDeVie0;
    private boundary.components.JPointDeVie jPointDeVie2;
    private boundary.components.JPointDeVie jPointDeVie3;
    private boundary.components.JPointDeVie jPointDeVie4;
    private boundary.components.JPointDeVie jPointDeVie5;
    private boundary.components.JPointDeVie jPointDeVie6;
    private boundary.components.JPointDeVie jPointDeVie7;
    private boundary.components.JPointDeVie jPointDeVie8;
    private boundary.components.JPointDeVie jPointDeVie9;
    private javax.swing.JSeparator jSeparator1;
    private boundary.components.JPanelWithBackground jaugePopulariteP1;
    private boundary.components.JPanelWithBackground jaugePopulariteP2;
    private boundary.components.JPanelWithBackground plateauBackground;
    private boundary.components.JPanelWithBackground plateauBackground1;
    // End of variables declaration//GEN-END:variables
}
