/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary;

import boundary.components.PopUpVictory;
import boundary.components.JCarte;
import boundary.components.JMainJoueur;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Frame;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author leo et yannf et Vincent
 */
public class Plateau extends javax.swing.JPanel {
    private BoundaryJeu boundaryJeu;
    
    private String nomPirate1;
    private String nomPirate2; 
    private boolean faitNuit = false; //donc jour
   
    /**
     * Creates new form Plateau
     * 
     */
    public Plateau() {
        initComponents();
        plateauBackground.setImage("PlateauJour.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        plateauBackground = new boundary.components.JPanelWithBackground();
        jPioche1 = new boundary.components.JPioche();
        jZoneInteraction1 = new boundary.components.JZoneInteraction();
        jPirateIcon2 = new boundary.components.JPirateIcon();
        jMainJoueur2 = new boundary.components.JMainJoueur();
        jInfoJoueur2 = new boundary.components.JInfoJoueur();
        jInfoJoueur1 = new boundary.components.JInfoJoueur();
        jMainJoueur1 = new boundary.components.JMainJoueur();
        jPirateIcon1 = new boundary.components.JPirateIcon();
        jLancerPiece1 = new boundary.components.JLancerPiece();
        jButtonFinDeTour = new boundary.components.JButtonCustom();

        setMinimumSize(new java.awt.Dimension(720, 480));

        plateauBackground.setMinimumSize(new java.awt.Dimension(720, 480));
        plateauBackground.setPreferredSize(new java.awt.Dimension(720, 480));
        plateauBackground.setLayout(new java.awt.GridBagLayout());

        jPioche1.setMinimumSize(new java.awt.Dimension(130, 80));
        jPioche1.setPreferredSize(new java.awt.Dimension(130, 80));
        jPioche1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPioche1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPioche1Layout = new javax.swing.GroupLayout(jPioche1);
        jPioche1.setLayout(jPioche1Layout);
        jPioche1Layout.setHorizontalGroup(
            jPioche1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPioche1Layout.setVerticalGroup(
            jPioche1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.18;
        gridBagConstraints.weighty = 0.19;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 70, 0);
        plateauBackground.add(jPioche1, gridBagConstraints);

        jZoneInteraction1.setMinimumSize(new java.awt.Dimension(420, 160));
        jZoneInteraction1.setPreferredSize(new java.awt.Dimension(460, 160));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.64;
        gridBagConstraints.weighty = 1.0;
        plateauBackground.add(jZoneInteraction1, gridBagConstraints);

        jPirateIcon2.setBackground(new java.awt.Color(255, 255, 204));
        jPirateIcon2.setMinimumSize(new java.awt.Dimension(130, 130));
        jPirateIcon2.setPreferredSize(new java.awt.Dimension(130, 130));
        jPirateIcon2.setImage("IconP2.png");

        javax.swing.GroupLayout jPirateIcon2Layout = new javax.swing.GroupLayout(jPirateIcon2);
        jPirateIcon2.setLayout(jPirateIcon2Layout);
        jPirateIcon2Layout.setHorizontalGroup(
            jPirateIcon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPirateIcon2Layout.setVerticalGroup(
            jPirateIcon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.18;
        gridBagConstraints.weighty = 0.27;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        plateauBackground.add(jPirateIcon2, gridBagConstraints);

        jMainJoueur2.setBackground(new java.awt.Color(255, 204, 204));
        jMainJoueur2.setMinimumSize(new java.awt.Dimension(420, 160));
        jMainJoueur2.setPreferredSize(new java.awt.Dimension(420, 160));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.64;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        plateauBackground.add(jMainJoueur2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.18;
        gridBagConstraints.weighty = 0.27;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        plateauBackground.add(jInfoJoueur2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 0.18;
        gridBagConstraints.weighty = 0.27;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        plateauBackground.add(jInfoJoueur1, gridBagConstraints);

        jMainJoueur1.setBackground(new java.awt.Color(255, 153, 153));
        jMainJoueur1.setMinimumSize(new java.awt.Dimension(420, 160));
        jMainJoueur1.setPreferredSize(new java.awt.Dimension(420, 160));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 0.64;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        plateauBackground.add(jMainJoueur1, gridBagConstraints);

        jPirateIcon1.setBackground(new java.awt.Color(255, 255, 204));
        jPirateIcon1.setMinimumSize(new java.awt.Dimension(130, 130));
        jPirateIcon1.setPreferredSize(new java.awt.Dimension(130, 130));
        jPirateIcon1.setImage("IconP1.png");

        javax.swing.GroupLayout jPirateIcon1Layout = new javax.swing.GroupLayout(jPirateIcon1);
        jPirateIcon1.setLayout(jPirateIcon1Layout);
        jPirateIcon1Layout.setHorizontalGroup(
            jPirateIcon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPirateIcon1Layout.setVerticalGroup(
            jPirateIcon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weightx = 0.18;
        gridBagConstraints.weighty = 0.27;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        plateauBackground.add(jPirateIcon1, gridBagConstraints);

        jLancerPiece1.setBackground(new java.awt.Color(255, 153, 153));
        jLancerPiece1.setMinimumSize(new java.awt.Dimension(130, 160));
        jLancerPiece1.setPreferredSize(new java.awt.Dimension(130, 160));

        javax.swing.GroupLayout jLancerPiece1Layout = new javax.swing.GroupLayout(jLancerPiece1);
        jLancerPiece1.setLayout(jLancerPiece1Layout);
        jLancerPiece1Layout.setHorizontalGroup(
            jLancerPiece1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jLancerPiece1Layout.setVerticalGroup(
            jLancerPiece1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 2, 0);
        plateauBackground.add(jLancerPiece1, gridBagConstraints);

        jButtonFinDeTour.setBackground(new java.awt.Color(137, 70, 33));
        jButtonFinDeTour.setForeground(new java.awt.Color(171, 75, 13));
        jButtonFinDeTour.setText("Fin de Tour");
        jButtonFinDeTour.setEnabled(false);
        jButtonFinDeTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinDeTourActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(127, 20, 30, 20);
        plateauBackground.add(jButtonFinDeTour, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plateauBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plateauBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPioche1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPioche1MouseClicked
        if(!jPioche1.isEnabled()) {return;}
        int tour = boundaryJeu.getTour();
        
        //get carte from noyeau
        List<String> listNomCarte = boundaryJeu.piocherCarte();
        
        JMainJoueur mainJoueur = (tour % 2 == 0) ? jMainJoueur1 : jMainJoueur2;
        
        for (String nomCarte : listNomCarte) {
            if (nomCarte == null) {
                System.out.println("Carte null détectée !");
                continue;
            }

            mainJoueur.ajouterCarte(
                nomCarte,
                boundaryJeu.getCarteId(nomCarte),
                boundaryJeu.getTypeCarte(nomCarte),
                boundaryJeu.getDescription(nomCarte),
                boundaryJeu.getZoneDepot(nomCarte)                  
                );
            mainJoueur.revalidate();
            mainJoueur.repaint();
        }
        
        mainJoueur.setEnabled(true);
        jPioche1.setEnabled(false);
    }//GEN-LAST:event_jPioche1MouseClicked

    private void jButtonFinDeTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinDeTourActionPerformed
        int tour = boundaryJeu.getTour();
        int joueurActuel = tour % 2;
        int joueurSuivant = (tour + 1) % 2;

        // Désactiver joueur actuel et retourner ses cartes
        if (joueurActuel == 0) {
            jMainJoueur1.setEnabled(false);
            retournerCartesMain(jMainJoueur1.getMainJoueur());
            jMainJoueur1.repaint();
        } else {
            jMainJoueur2.setEnabled(false);
            retournerCartesMain(jMainJoueur2.getMainJoueur());
            jMainJoueur2.repaint();
        }

        // Afficher popup 
        JPanel panel = new JPanel();
        panel.setBackground(new Color(139, 69, 19)); // marron foncé
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        JLabel message = new JLabel("<html><div style='text-align: center; color: white;'><h2>Tour terminé</h2><p>Cliquez pour continuer</p></div></html>");
        message.setAlignmentX(Component.CENTER_ALIGNMENT);

        JButton bouton = new JButton("Commencer le tour suivant");
        bouton.setAlignmentX(Component.CENTER_ALIGNMENT);
        bouton.setBackground(new Color(210, 180, 140)); // marron clair
        bouton.setForeground(Color.BLACK);
        bouton.setFocusPainted(false);
        bouton.setFont(new Font("SansSerif", Font.BOLD, 14));

        panel.add(message);
        panel.add(Box.createRigidArea(new Dimension(0, 20)));
        panel.add(bouton);

        // Création de la boîte de dialogue personnalisée
        JDialog dialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), "Changement de tour", true);
        dialog.setUndecorated(false); // garde la bordure standard
        dialog.getContentPane().add(panel);
        dialog.pack();
        dialog.setLocationRelativeTo(SwingUtilities.getWindowAncestor(this));

        // Action bouton : fermer la boîte
        bouton.addActionListener(e -> dialog.dispose());

        // Affiche la boîte (modal)
        dialog.setVisible(true);

        // Activer joueur suivant et retourner ses cartes
        if (joueurSuivant == 0) {
            retournerCartesMain(jMainJoueur1.getMainJoueur());
            jMainJoueur1.setEnabled(false);
            jMainJoueur1.repaint();
        } else {
            retournerCartesMain(jMainJoueur2.getMainJoueur());
            jMainJoueur2.setEnabled(false);
            jMainJoueur2.repaint();
        }

        jButtonFinDeTour.setEnabled(false);
        jPioche1.setEnabled(true);
        boundaryJeu.incrementerTour();
        updatePlateau();
    }//GEN-LAST:event_jButtonFinDeTourActionPerformed

    
    private void updatePlateau(){
        boolean newEtat = boundaryJeu.isNuit();
        if(newEtat != faitNuit){
            faitNuit = newEtat;
            //Peut être à faire dans un nouveau thread
            if(newEtat){ plateauBackground.setImage("PlateauNuit.png");}
            else {plateauBackground.setImage("PlateauJour.png");}
            plateauBackground.revalidate();
            plateauBackground.repaint();
        }
    }
    
    
    public String getCurrentPirate(){
        int tour = boundaryJeu.getTour();
        if(tour%2 == 0){
            return boundaryJeu.getPirateName(0);
        } else {
            return boundaryJeu.getPirateName(1);
        }
    }
    
    public void setBoundaryJeu(BoundaryJeu boundaryJeu){
        if (this.boundaryJeu == null){
            this.boundaryJeu = boundaryJeu;
            this.nomPirate1 = boundaryJeu.getPirateName(0);
            this.nomPirate2 = boundaryJeu.getPirateName(1);
            jZoneInteraction1.initZoneDepot(nomPirate1, nomPirate2);
            jPirateIcon1.setNomPirate(nomPirate1);
            jPirateIcon2.setNomPirate(nomPirate2);
            
            initPlateau();
        }
    }
    
    private void initPlateau (){
        //Init Pirate
        jInfoJoueur1.initJoueur(nomPirate1, 0, jMainJoueur1, boundaryJeu);  // utile ?
        jInfoJoueur2.initJoueur(nomPirate2, 1, jMainJoueur2, boundaryJeu);  // utile ?

        //Init info
        updateInfoPirate();

        //Init Main Joueur
        initMainJoueur(jMainJoueur1, 0);
        initMainJoueur(jMainJoueur2, 1);
        retournerCartesMain(jMainJoueur2.getMainJoueur());
        jMainJoueur2.setEnabled(false);
        jMainJoueur1.setEnabled(false);
        jButtonFinDeTour.setEnabled(false);
    }

    private void evenementJeu(List<String> evenements, JMainJoueur mainAdversaire) {
        Thread animationThread = new Thread(() -> {
            for (String e : evenements) {
                switch (e) {
                    case "0" -> {
                        jLancerPiece1.setEtat("P");
                        sleep1s(); 
                    }case "1" -> {
                        jLancerPiece1.setEtat("F");
                        sleep1s();  
                    }default -> {
                        if (e.contains("Toucher d'encre")) {
                            String[] res = e.split(":");
                            String cardName = res[res.length - 1].trim();
                            mainAdversaire.deleteCardName(cardName);
                            mainAdversaire.revalidate();
                            mainAdversaire.repaint();
                        }
                    }
                }
            }
        });
        animationThread.start();
    }

    private void sleep1s(){
        try {
            Thread.sleep(1000); // Wait 1 second between animations
        } catch (InterruptedException ex) {
            Thread.currentThread().interrupt();
        }
    }
    
    public BoundaryJeu getBoundaryJeu() {
        return boundaryJeu;
    }
    
    private void updateInfoPirate(){
        jInfoJoueur1.finTour();
        jInfoJoueur2.finTour();
    }

    private void victory (String winner){
        PopUpVictory victoire = new PopUpVictory((JFrame) this.getTopLevelAncestor(),winner);
        victoire.setVisible(true);
    }
  
    public void jouerTour(JCarte carte){
        int tour = boundaryJeu.getTour();
        List<String> resultat = boundaryJeu.jouerCarte(carte);
        updateInfoPirate();
            // Détermine les mains des joueurs selon le tour
        JMainJoueur mainJoueur = (tour % 2 == 0) ? jMainJoueur1 : jMainJoueur2;
        JMainJoueur mainAdversaire = (tour % 2 == 0) ? jMainJoueur2 : jMainJoueur1;
            // Lance les animations/effets du tour
        evenementJeu(resultat, mainAdversaire);
            // Vérifie la victoire
        String dernierResultat = resultat.getLast();
        if (!dernierResultat.equals("Pas de gagnant")){
            victory(dernierResultat);  // Affiche écran de victoire
            System.out.println("Gagnant : " + dernierResultat);
        }
            // Supprime la carte jouée
        mainJoueur.deleteCard(carte);     
            // Active / désactive les bonnes zones de l'IHM
        setEtatInterfaceFinDeTour();
    }
    
    private void setEtatInterfaceFinDeTour() {
        jMainJoueur1.setEnabled(false);
        jMainJoueur2.setEnabled(false);
        jButtonFinDeTour.setEnabled(true);
        jPioche1.setEnabled(false);
    }
    
    public void retournerCartes() {
        retournerCartesMain(jMainJoueur2.getMainJoueur());
        retournerCartesMain(jMainJoueur1.getMainJoueur());
    }
    private void retournerCartesMain(List<JCarte> main){
        for (JCarte jCarte : main) {
            jCarte.changeCardFace();
        }
    }

    private void initMainJoueur(JMainJoueur jMainJoueur, int idPirate){
        jMainJoueur.setIdPirate(idPirate);
        for (String nomCarte : boundaryJeu.getPirateMain(idPirate)) {
            jMainJoueur.ajouterCarte(nomCarte, boundaryJeu.getCarteId(nomCarte), boundaryJeu.getTypeCarte(nomCarte),
                    boundaryJeu.getDescription(nomCarte), boundaryJeu.getZoneDepot(nomCarte));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private boundary.components.JButtonCustom jButtonFinDeTour;
    private boundary.components.JInfoJoueur jInfoJoueur1;
    private boundary.components.JInfoJoueur jInfoJoueur2;
    private boundary.components.JLancerPiece jLancerPiece1;
    private boundary.components.JMainJoueur jMainJoueur1;
    private boundary.components.JMainJoueur jMainJoueur2;
    private boundary.components.JPioche jPioche1;
    private boundary.components.JPirateIcon jPirateIcon1;
    private boundary.components.JPirateIcon jPirateIcon2;
    private boundary.components.JZoneInteraction jZoneInteraction1;
    public boundary.components.JPanelWithBackground plateauBackground;
    // End of variables declaration//GEN-END:variables
}
