/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary;

import boundary.components.JCarte;
import boundary.components.JMainJoueur;
import boundary.components.JZoneInteraction;
import java.util.List;
import noyau.GestionnaireCartes;
import noyau.GestionnaireEffetFumee;

/**
 *
 * @author yannf
 */
public class Plateau extends javax.swing.JPanel {
    private BoundaryJeu boundaryJeu;
    private JZoneInteraction zoneInteraction = null;
    private JCarte carte;
    private GestionnaireCartes gestionnaire = new GestionnaireCartes();
    private GestionnaireEffetFumee gestionnairefumee = new GestionnaireEffetFumee();
    
    private String nomPirate1;
    private String nomPirate2;
    
    /**
     * Creates new form Plateau
     */
    public Plateau() {
        initComponents();
        //TODO Set Boundary
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plateauBackground = new boundary.components.JPanelWithBackground();
        iconP1 = new boundary.components.JPanelWithBackground();
        iconP2 = new boundary.components.JPanelWithBackground();
        jMainJoueur2 = new boundary.components.JMainJoueur();
        jMainJoueur1 = new boundary.components.JMainJoueur();
        jInfoJoueur1 = new boundary.components.JInfoJoueur();
        jInfoJoueur2 = new boundary.components.JInfoJoueur();
        jPioche1 = new boundary.components.JPioche();
        jZoneInteraction1 = new boundary.components.JZoneInteraction();

        plateauBackground.setBackground(new java.awt.Color(255, 204, 204));
        plateauBackground.setImage("Plateau.png");
        plateauBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconP1.setBackground(new java.awt.Color(255, 255, 204));
        iconP1.setPreferredSize(new java.awt.Dimension(130, 130));
        iconP1.setImage("IconP1.png");

        javax.swing.GroupLayout iconP1Layout = new javax.swing.GroupLayout(iconP1);
        iconP1.setLayout(iconP1Layout);
        iconP1Layout.setHorizontalGroup(
            iconP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        iconP1Layout.setVerticalGroup(
            iconP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        plateauBackground.add(iconP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, -1, -1));

        iconP2.setBackground(new java.awt.Color(255, 255, 204));
        iconP2.setPreferredSize(new java.awt.Dimension(130, 130));
        iconP2.setImage("IconP2.png");

        javax.swing.GroupLayout iconP2Layout = new javax.swing.GroupLayout(iconP2);
        iconP2.setLayout(iconP2Layout);
        iconP2Layout.setHorizontalGroup(
            iconP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        iconP2Layout.setVerticalGroup(
            iconP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        plateauBackground.add(iconP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        plateauBackground.add(jMainJoueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));
        plateauBackground.add(jMainJoueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));
        plateauBackground.add(jInfoJoueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, -1));
        plateauBackground.add(jInfoJoueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        jPioche1.setPreferredSize(new java.awt.Dimension(142, 90));
        jPioche1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPioche1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPioche1Layout = new javax.swing.GroupLayout(jPioche1);
        jPioche1.setLayout(jPioche1Layout);
        jPioche1Layout.setHorizontalGroup(
            jPioche1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );
        jPioche1Layout.setVerticalGroup(
            jPioche1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        plateauBackground.add(jPioche1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));
        plateauBackground.add(jZoneInteraction1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plateauBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plateauBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPioche1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPioche1MouseClicked
        if(!jPioche1.isEnabled()) {return;}
        int tour = boundaryJeu.getTour();
        
        //get carte from noyeau
        List<String> listNomCarte = boundaryJeu.piocherCarte();

    
        if (tour%2 == 0){
            for(String nomCarte : listNomCarte){
                //System.out.println("Nom de carte J1 = " + nomCarte + "\n");
                jMainJoueur1.ajouterCarte(nomCarte, boundaryJeu.getCarteId(nomCarte),
                        boundaryJeu.getTypeCarte(nomCarte), boundaryJeu.getDescription(nomCarte),
                        boundaryJeu.getZoneDepot(nomCarte));
                jMainJoueur1.repaint();
            }
            jMainJoueur1.setEnabled(true);
        } else if (tour%2 == 1){
            for(String nomCarte : listNomCarte){
                //System.out.println("Nom de carte J2 = " + nomCarte + "\n");
                jMainJoueur2.ajouterCarte(nomCarte, boundaryJeu.getCarteId(nomCarte),
                        boundaryJeu.getTypeCarte(nomCarte), boundaryJeu.getDescription(nomCarte), 
                        boundaryJeu.getZoneDepot(nomCarte));
                jMainJoueur2.repaint();
            }
            jMainJoueur2.setEnabled(true);
        }
        jPioche1.setEnabled(false);
    }//GEN-LAST:event_jPioche1MouseClicked

    
    public String getCurrentPirate(){
        int tour = boundaryJeu.getTour();
        if(tour%2 == 0){
            return boundaryJeu.getPirateName(0);
        } else {
            return boundaryJeu.getPirateName(1);
        }
    }
    
    public void setBoundaryJeu(BoundaryJeu boundaryJeu){
        if (this.boundaryJeu == null){
            this.boundaryJeu = boundaryJeu;
            this.nomPirate1 = boundaryJeu.getPirateName(0);
            this.nomPirate2 = boundaryJeu.getPirateName(1);
            jZoneInteraction1.initZoneDepot(nomPirate1, nomPirate2);
            
            initPlateau();
        }
    }
    
    private void initPlateau (){
        //Init info
        updateInfoPirate();

        //Init Main Joueur
        initMainJoueur(jMainJoueur1, 0);
        initMainJoueur(jMainJoueur2, 1);
        retournerCartesMain(jMainJoueur2.getMainJoueur());
        jMainJoueur2.setEnabled(false);
        jMainJoueur1.setEnabled(false);
    }
    
    public BoundaryJeu getBoundaryJeu(){
        return boundaryJeu;
    }
    
    private void updateInfoPirate(){
        jInfoJoueur1.finTour();
        jInfoJoueur2.finTour();
    }
    public void jouerTour(JCarte carte){
        List<String> resultat = boundaryJeu.jouerCarte(carte);
        updateInfoPirate();
        
        String lastElement = resultat.get(resultat.size()-1);
        if (!lastElement.equals("Pas de gagnant")){
            //afficherGagnant(lastElement);
            System.out.println("Gagnant : " + lastElement);
        }
        jPioche1.setEnabled(true);
        jMainJoueur1.setEnabled(!jMainJoueur1.isEnabled());
        jMainJoueur2.setEnabled(!jMainJoueur2.isEnabled());
        retournerCartes();
    }
    
    public void retournerCartes() {
        retournerCartesMain(jMainJoueur2.getMainJoueur());
        retournerCartesMain(jMainJoueur1.getMainJoueur());
    }
    
    private void retournerCartesMain(List<JCarte> main){
        for (JCarte jCarte : main) {
            jCarte.changeCardFace();
        }
    }

    private void initMainJoueur(JMainJoueur jMainJoueur, int idPirate){
        jMainJoueur.setIdPirate(idPirate);
        for (String nomCarte : boundaryJeu.getPirateMain(idPirate)) {
            jMainJoueur.ajouterCarte(nomCarte, boundaryJeu.getCarteId(nomCarte), boundaryJeu.getTypeCarte(nomCarte),
                    boundaryJeu.getDescription(nomCarte), boundaryJeu.getZoneDepot(nomCarte));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private boundary.components.JPanelWithBackground iconP1;
    private boundary.components.JPanelWithBackground iconP2;
    private boundary.components.JInfoJoueur jInfoJoueur1;
    private boundary.components.JInfoJoueur jInfoJoueur2;
    private boundary.components.JMainJoueur jMainJoueur1;
    private boundary.components.JMainJoueur jMainJoueur2;
    private boundary.components.JPioche jPioche1;
    private boundary.components.JZoneInteraction jZoneInteraction1;
    private boundary.components.JPanelWithBackground plateauBackground;
    // End of variables declaration//GEN-END:variables
}
