package boundary;

import boundary.components.Point_de_vie;
import boundary.component_manager.GestionnaireCartes;
import boundary.components.JCarte;
import boundary.components.Zone_d_interaction;
import java.awt.Component;
import java.awt.Rectangle;
import java.io.File;
import java.io.IOException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author choue
 */
public class Plateau extends javax.swing.JPanel {

    private Zone_d_interaction zoneInteraction;
    private JCarte carte ;
    private GestionnaireCartes gestionnaire;
    /**
     * Creates new form Plateau
     */
    public Plateau() {
        initComponents();
        this.zoneInteraction = null;
        this.gestionnaire = new GestionnaireCartes();
        initComponents();
        zoneInteraction = zone_d_interaction1;
        
        carte = jCarte1;
        jCarte1.changeCardFace();
        gestionnaire.ajouterCarte(jCarte1);
        carte = jCarte2;
        gestionnaire.ajouterCarte(jCarte2);
        gestionnaire.ajouterZone(zone_d_interaction1);
        setNbViesRestantes(4);
        
        imageJ1.setImage("boundary_ressources/IconJ1.png");
        imageJ2.setImage("boundary_ressources/IconJ2.png");
        ZonePop1.setImage("boundary_ressources/Icon12.png");
        ZonePop2.setImage("boundary_ressources/Icon23.png");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //Je comprends pas pourquoi ça comprend pas ce truc
    public GestionnaireCartes getGestionnaire() {
        return gestionnaire;
    }
   
    public void verifierZoneInteraction(Rectangle boundsCarte) {
	zone_d_interaction1.verifierCarte(carte);
        Rectangle boundsZone = zoneInteraction.getBounds();
        if (boundsZone.intersects(boundsCarte)) {
            //JOptionPane.showMessageDialog(this, "Carte déposée dans la zone !");    // debuggage
        }
    }
    public void setNbViesRestantes(int n) {
        Component[] composants = JaugePoint_de_vie1.getComponents();
        for (int i = 0; i < composants.length; i++) {
            if (composants[i] instanceof Point_de_vie coeur) {
                coeur.setEtat(i < n); // les premiers pleins, le reste vides
            }
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Zone_Speciale = new boundary.components.Zone_d_interaction();
        zone_d_interaction10 = new boundary.components.Zone_d_interaction();
        zone_d_interaction9 = new boundary.components.Zone_d_interaction();
        zone_d_interaction2 = new boundary.components.Zone_d_interaction();
        zone_d_interaction4 = new boundary.components.Zone_d_interaction();
        ZonePop1 = new boundary.components.ImagePanel();
        imageJ1 = new boundary.components.ImagePanel();
        imageJ2 = new boundary.components.ImagePanel();
        JaugePoint_de_vie1 = new javax.swing.JPanel();
        point_de_vie1 = new boundary.components.Point_de_vie();
        point_de_vie2 = new boundary.components.Point_de_vie();
        point_de_vie3 = new boundary.components.Point_de_vie();
        point_de_vie4 = new boundary.components.Point_de_vie();
        point_de_vie5 = new boundary.components.Point_de_vie();
        JaugePoint_de_vie2 = new javax.swing.JPanel();
        point_de_vie6 = new boundary.components.Point_de_vie();
        point_de_vie7 = new boundary.components.Point_de_vie();
        point_de_vie9 = new boundary.components.Point_de_vie();
        point_de_vie10 = new boundary.components.Point_de_vie();
        point_de_vie8 = new boundary.components.Point_de_vie();
        ZonePop2 = new boundary.components.ImagePanel();
        zone_d_interaction1 = new boundary.components.Zone_d_interaction();
        jLabel1 = new javax.swing.JLabel();
        MainJ1 = new boundary.components.Zone_d_interaction();
        jCarte2 = new boundary.components.JCarte();
        jCarte1 = new boundary.components.JCarte();
        MainJ2 = new boundary.components.Zone_d_interaction();

        setPreferredSize(new java.awt.Dimension(720, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Zone_Speciale.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout zone_d_interaction10Layout = new javax.swing.GroupLayout(zone_d_interaction10);
        zone_d_interaction10.setLayout(zone_d_interaction10Layout);
        zone_d_interaction10Layout.setHorizontalGroup(
            zone_d_interaction10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );
        zone_d_interaction10Layout.setVerticalGroup(
            zone_d_interaction10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        Zone_Speciale.add(zone_d_interaction10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        javax.swing.GroupLayout zone_d_interaction9Layout = new javax.swing.GroupLayout(zone_d_interaction9);
        zone_d_interaction9.setLayout(zone_d_interaction9Layout);
        zone_d_interaction9Layout.setHorizontalGroup(
            zone_d_interaction9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        zone_d_interaction9Layout.setVerticalGroup(
            zone_d_interaction9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        Zone_Speciale.add(zone_d_interaction9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        javax.swing.GroupLayout zone_d_interaction2Layout = new javax.swing.GroupLayout(zone_d_interaction2);
        zone_d_interaction2.setLayout(zone_d_interaction2Layout);
        zone_d_interaction2Layout.setHorizontalGroup(
            zone_d_interaction2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        zone_d_interaction2Layout.setVerticalGroup(
            zone_d_interaction2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        Zone_Speciale.add(zone_d_interaction2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        javax.swing.GroupLayout zone_d_interaction4Layout = new javax.swing.GroupLayout(zone_d_interaction4);
        zone_d_interaction4.setLayout(zone_d_interaction4Layout);
        zone_d_interaction4Layout.setHorizontalGroup(
            zone_d_interaction4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        zone_d_interaction4Layout.setVerticalGroup(
            zone_d_interaction4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        Zone_Speciale.add(zone_d_interaction4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        add(Zone_Speciale, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 460, 180));

        javax.swing.GroupLayout ZonePop1Layout = new javax.swing.GroupLayout(ZonePop1);
        ZonePop1.setLayout(ZonePop1Layout);
        ZonePop1Layout.setHorizontalGroup(
            ZonePop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        ZonePop1Layout.setVerticalGroup(
            ZonePop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        add(ZonePop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, 150));

        javax.swing.GroupLayout imageJ1Layout = new javax.swing.GroupLayout(imageJ1);
        imageJ1.setLayout(imageJ1Layout);
        imageJ1Layout.setHorizontalGroup(
            imageJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        imageJ1Layout.setVerticalGroup(
            imageJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        add(imageJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 130, -1));

        javax.swing.GroupLayout imageJ2Layout = new javax.swing.GroupLayout(imageJ2);
        imageJ2.setLayout(imageJ2Layout);
        imageJ2Layout.setHorizontalGroup(
            imageJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        imageJ2Layout.setVerticalGroup(
            imageJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        add(imageJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, -1));

        javax.swing.GroupLayout point_de_vie1Layout = new javax.swing.GroupLayout(point_de_vie1);
        point_de_vie1.setLayout(point_de_vie1Layout);
        point_de_vie1Layout.setHorizontalGroup(
            point_de_vie1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie1Layout.setVerticalGroup(
            point_de_vie1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie1.add(point_de_vie1);

        javax.swing.GroupLayout point_de_vie2Layout = new javax.swing.GroupLayout(point_de_vie2);
        point_de_vie2.setLayout(point_de_vie2Layout);
        point_de_vie2Layout.setHorizontalGroup(
            point_de_vie2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie2Layout.setVerticalGroup(
            point_de_vie2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie1.add(point_de_vie2);

        javax.swing.GroupLayout point_de_vie3Layout = new javax.swing.GroupLayout(point_de_vie3);
        point_de_vie3.setLayout(point_de_vie3Layout);
        point_de_vie3Layout.setHorizontalGroup(
            point_de_vie3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie3Layout.setVerticalGroup(
            point_de_vie3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie1.add(point_de_vie3);

        javax.swing.GroupLayout point_de_vie4Layout = new javax.swing.GroupLayout(point_de_vie4);
        point_de_vie4.setLayout(point_de_vie4Layout);
        point_de_vie4Layout.setHorizontalGroup(
            point_de_vie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie4Layout.setVerticalGroup(
            point_de_vie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie1.add(point_de_vie4);

        javax.swing.GroupLayout point_de_vie5Layout = new javax.swing.GroupLayout(point_de_vie5);
        point_de_vie5.setLayout(point_de_vie5Layout);
        point_de_vie5Layout.setHorizontalGroup(
            point_de_vie5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie5Layout.setVerticalGroup(
            point_de_vie5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie1.add(point_de_vie5);

        add(JaugePoint_de_vie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 30, 150));

        javax.swing.GroupLayout point_de_vie6Layout = new javax.swing.GroupLayout(point_de_vie6);
        point_de_vie6.setLayout(point_de_vie6Layout);
        point_de_vie6Layout.setHorizontalGroup(
            point_de_vie6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie6Layout.setVerticalGroup(
            point_de_vie6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie2.add(point_de_vie6);

        javax.swing.GroupLayout point_de_vie7Layout = new javax.swing.GroupLayout(point_de_vie7);
        point_de_vie7.setLayout(point_de_vie7Layout);
        point_de_vie7Layout.setHorizontalGroup(
            point_de_vie7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie7Layout.setVerticalGroup(
            point_de_vie7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie2.add(point_de_vie7);

        javax.swing.GroupLayout point_de_vie9Layout = new javax.swing.GroupLayout(point_de_vie9);
        point_de_vie9.setLayout(point_de_vie9Layout);
        point_de_vie9Layout.setHorizontalGroup(
            point_de_vie9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie9Layout.setVerticalGroup(
            point_de_vie9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie2.add(point_de_vie9);

        javax.swing.GroupLayout point_de_vie10Layout = new javax.swing.GroupLayout(point_de_vie10);
        point_de_vie10.setLayout(point_de_vie10Layout);
        point_de_vie10Layout.setHorizontalGroup(
            point_de_vie10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie10Layout.setVerticalGroup(
            point_de_vie10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie2.add(point_de_vie10);

        javax.swing.GroupLayout point_de_vie8Layout = new javax.swing.GroupLayout(point_de_vie8);
        point_de_vie8.setLayout(point_de_vie8Layout);
        point_de_vie8Layout.setHorizontalGroup(
            point_de_vie8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie8Layout.setVerticalGroup(
            point_de_vie8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie2.add(point_de_vie8);

        add(JaugePoint_de_vie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 30, 150));

        javax.swing.GroupLayout ZonePop2Layout = new javax.swing.GroupLayout(ZonePop2);
        ZonePop2.setLayout(ZonePop2Layout);
        ZonePop2Layout.setHorizontalGroup(
            ZonePop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        ZonePop2Layout.setVerticalGroup(
            ZonePop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        add(ZonePop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, -1));

        jLabel1.setText("Pioche");

        javax.swing.GroupLayout zone_d_interaction1Layout = new javax.swing.GroupLayout(zone_d_interaction1);
        zone_d_interaction1.setLayout(zone_d_interaction1Layout);
        zone_d_interaction1Layout.setHorizontalGroup(
            zone_d_interaction1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zone_d_interaction1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        zone_d_interaction1Layout.setVerticalGroup(
            zone_d_interaction1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zone_d_interaction1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        add(zone_d_interaction1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 130, 180));

        MainJ1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        try{
            jCarte2.setImage("boundary_ressources/Card1FrontAttack.png");
        } catch (IOException e){
            System.out.print("Card not found");
        }

        javax.swing.GroupLayout jCarte2Layout = new javax.swing.GroupLayout(jCarte2);
        jCarte2.setLayout(jCarte2Layout);
        jCarte2Layout.setHorizontalGroup(
            jCarte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jCarte2Layout.setVerticalGroup(
            jCarte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        MainJ1.add(jCarte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 130));

        try{
            jCarte1.setImage("boundary_ressources/Card1FrontAttack.png");
        } catch (IOException e){
            System.out.print("Card not found");
        }

        javax.swing.GroupLayout jCarte1Layout = new javax.swing.GroupLayout(jCarte1);
        jCarte1.setLayout(jCarte1Layout);
        jCarte1Layout.setHorizontalGroup(
            jCarte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jCarte1Layout.setVerticalGroup(
            jCarte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        MainJ1.add(jCarte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 130));

        add(MainJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 460, 150));

        javax.swing.GroupLayout MainJ2Layout = new javax.swing.GroupLayout(MainJ2);
        MainJ2.setLayout(MainJ2Layout);
        MainJ2Layout.setHorizontalGroup(
            MainJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        MainJ2Layout.setVerticalGroup(
            MainJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        add(MainJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 460, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JaugePoint_de_vie1;
    private javax.swing.JPanel JaugePoint_de_vie2;
    private boundary.components.Zone_d_interaction MainJ1;
    private boundary.components.Zone_d_interaction MainJ2;
    private boundary.components.ImagePanel ZonePop1;
    private boundary.components.ImagePanel ZonePop2;
    private boundary.components.Zone_d_interaction Zone_Speciale;
    private boundary.components.ImagePanel imageJ1;
    private boundary.components.ImagePanel imageJ2;
    private boundary.components.JCarte jCarte1;
    private boundary.components.JCarte jCarte2;
    private javax.swing.JLabel jLabel1;
    private boundary.components.Point_de_vie point_de_vie1;
    private boundary.components.Point_de_vie point_de_vie10;
    private boundary.components.Point_de_vie point_de_vie2;
    private boundary.components.Point_de_vie point_de_vie3;
    private boundary.components.Point_de_vie point_de_vie4;
    private boundary.components.Point_de_vie point_de_vie5;
    private boundary.components.Point_de_vie point_de_vie6;
    private boundary.components.Point_de_vie point_de_vie7;
    private boundary.components.Point_de_vie point_de_vie8;
    private boundary.components.Point_de_vie point_de_vie9;
    private boundary.components.Zone_d_interaction zone_d_interaction1;
    private boundary.components.Zone_d_interaction zone_d_interaction10;
    private boundary.components.Zone_d_interaction zone_d_interaction2;
    private boundary.components.Zone_d_interaction zone_d_interaction4;
    private boundary.components.Zone_d_interaction zone_d_interaction9;
    // End of variables declaration//GEN-END:variables
}
